Repository samchon/typia, pull requests merged in 2022-10, with the labels that each got.

#215 Close #211, support `@default` tag for JSON schema
  package.json
  src/programmers/ApplicationProgrammer.ts
  src/programmers/internal/application_array.ts
  src/programmers/internal/application_boolean.ts
  src/programmers/internal/application_constant.ts
  src/programmers/internal/application_default.ts
  src/programmers/internal/application_default_string.ts
  src/programmers/internal/application_number.ts
  src/programmers/internal/application_object.ts
  src/programmers/internal/application_schema.ts
  src/programmers/internal/application_string.ts
  src/programmers/internal/application_templates.ts
  src/programmers/internal/application_tuple.ts
  src/programmers/internal/check_array.ts
  src/programmers/internal/check_everything.ts
  src/programmers/internal/check_length.ts
  src/programmers/internal/check_number.ts
  src/programmers/internal/check_object.ts
  src/programmers/internal/check_properties.ts
  src/programmers/internal/check_string.ts
  src/programmers/internal/check_string_tags.ts
  src/programmers/internal/check_template.ts
  src/programmers/internal/decode_union_object.ts
  src/programmers/internal/template_to_pattern.ts
  src/schemas/IJsonSchema.ts
  src/schemas/JsonTypeChecker.ts
  src/typings/Atomic.ts
  test/features/application/test_application_tag_default.ts
  test/features/application/test_application_ultimate_union.ts
  test/manual.js
  test/structures/TagDefault.ts
  tsconfig.json
Labels: enhancement

#217 Fix #216 - json schema's pattern does use `/`
  package.json
  src/programmers/internal/application_default_string.ts
  src/programmers/internal/application_templates.ts
  src/programmers/internal/metadata_to_pattern.ts
  src/programmers/internal/template_to_pattern.ts
  src/utils/PatternUtil.ts
  test/features/application/test_application_tag_default.ts
  test/features/application/test_application_template_atomic.ts
  test/features/application/test_application_template_union.ts
Labels: bug

#219 Developing #153 and Close #218 - support JSON schema
  package.json
  src/factories/internal/emplace_metadata_object.ts
  src/metadata/MetadataProperty.ts
  src/programmers/internal/application_object.ts
  src/schemas/IJsonComponents.ts
  test/features/application/test_application_dynamic_composite.ts
  test/features/application/test_application_dynamic_simple.ts
  test/features/application/test_application_dynamic_template.ts
  test/features/application/test_application_dynamic_union.ts
  test/features/application/test_application_ultimate_union.ts
  test/manual.js
  test/structures/DynamicComposite.ts
  test/structures/DynamicSimple.ts
  test/structures/DynamicTemplate.ts
  test/structures/DynamicUnion.ts
Labels: enhancement

#221 Close #220 - validators support dynamic properties
  README.md
  package.json
  src/metadata/Metadata.ts
  src/module.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/helpers/StringifyJoinder.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/check_object.ts
  src/programmers/internal/check_properties.ts
  src/programmers/internal/check_template.ts
  src/utils/PatternUtil.ts
  test/features/application/test_application_dynamic_composite.ts
  test/features/application/test_application_dynamic_template.ts
  test/features/application/test_application_dynamic_union.ts
  test/features/application/test_application_template_atomic.ts
  test/features/application/test_application_template_union.ts
  test/features/assert/test_assert_dynamic_composite.ts
  test/features/assert/test_assert_dynamic_simple.ts
  test/features/assert/test_assert_dynamic_template.ts
  test/features/assert/test_assert_dynamic_tree.ts
  test/features/assert/test_assert_dynamic_union.ts
  test/features/assert_equals/_test_assert_equals.ts
  test/features/assert_equals/test_assert_equals_dynamic_composite.ts
  test/features/assert_equals/test_assert_equals_dynamic_simple.ts
  test/features/assert_equals/test_assert_equals_dynamic_template.ts
  test/features/assert_equals/test_assert_equals_dynamic_tree.ts
  test/features/assert_equals/test_assert_equals_dynamic_union.ts
  test/features/equals/_test_equals.ts
  test/features/equals/test_equals_dynamic_composite.ts
  test/features/equals/test_equals_dynamic_simple.ts
  test/features/equals/test_equals_dynamic_template.ts
  test/features/equals/test_equals_dynamic_tree.ts
  test/features/equals/test_equals_dynamic_union.ts
  test/features/is/_test_is.ts
  test/features/is/test_is_dynamic_composite.ts
  test/features/is/test_is_dynamic_simple.ts
  test/features/is/test_is_dynamic_template.ts
  test/features/is/test_is_dynamic_tree.ts
  test/features/is/test_is_dynamic_union.ts
  test/features/validate/test_validate_dynamic_composite.ts
  test/features/validate/test_validate_dynamic_simple.ts
  test/features/validate/test_validate_dynamic_template.ts
  test/features/validate/test_validate_dynamic_tree.ts
  test/features/validate/test_validate_dynamic_union.ts
  test/features/validate_equals/_test_validate_equals.ts
  test/features/validate_equals/test_validate_equals_dynamic_composite.ts
  test/features/validate_equals/test_validate_equals_dynamic_simple.ts
  test/features/validate_equals/test_validate_equals_dynamic_template.ts
  test/features/validate_equals/test_validate_equals_dynamic_tree.ts
  test/features/validate_equals/test_validate_equals_dynamic_union.ts
  test/manual.js
  test/structures/DynamicTree.ts
Labels: enhancement

#223 Enhance template to pattern converter
  package.json
  src/programmers/internal/application_object.ts
  src/programmers/internal/application_templates.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/check_template.ts
  src/programmers/internal/metadata_to_pattern.ts
  src/programmers/internal/template_to_pattern.ts
  src/utils/PatternUtil.ts
  test/features/application/test_application_dynamic_composite.ts
  test/features/application/test_application_dynamic_template.ts
  test/features/application/test_application_dynamic_union.ts
  test/features/application/test_application_tag_default.ts
  test/features/application/test_application_template_atomic.ts
  test/features/application/test_application_template_union.ts
Labels: enhancement

#225 Close #222 - `TSON.stringify()` supports dynamic properties
  package.json
  src/factories/internal/emplace_metadata_object.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/helpers/StringifyJoinder.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/stringify_dynamic_properties.ts
  src/programmers/internal/stringify_regular_properties.ts
  test/features/stringify/test_stringify_dynamic_composite.ts
  test/features/stringify/test_stringify_dynamic_simple.ts
  test/features/stringify/test_stringify_dynamic_template.ts
  test/features/stringify/test_stringify_dynamic_tree.ts
  test/features/stringify/test_stringify_dynamic_union.ts
  test/manual.js
Labels: enhancement

#227 Fix #226 - consider meta-programmed class type
  package.json
  src/factories/internal/emplace_metadata_object.ts
  src/transform.ts
  test/issues/226.ts
Labels: enhancement

#229 Close #228 - benchmark of `io-ts` and `zod`
  README.md
  benchmark/features/benchmark_assert.ts
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_validate.ts
  benchmark/index.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics        .md
  benchmark/results/charts.xlsx
  benchmark/results/v3.2/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/v3.2/charts.xlsx
  benchmark/structures/io-ts/IoTsArrayRecursive.ts
  benchmark/structures/io-ts/IoTsArrayRecursiveUnionExplicit.ts
  benchmark/structures/io-ts/IoTsArrayRecursiveUnionImplicit.ts
  benchmark/structures/io-ts/IoTsObjectHierarchical.ts
  benchmark/structures/io-ts/IoTsObjectRecursive.ts
  benchmark/structures/io-ts/IoTsObjectUnionExplicit.ts
  benchmark/structures/io-ts/IoTsObjectUnionImplicit.ts
  benchmark/structures/io-ts/IoTsUltimateUnion.ts
  benchmark/structures/zod/ZodArrayRecursive.ts
  benchmark/structures/zod/ZodArrayRecursiveUnionExplicit.ts
  benchmark/structures/zod/ZodArrayRecursiveUnionImplicit.ts
  benchmark/structures/zod/ZodObjectHierarchical.ts
  benchmark/structures/zod/ZodObjectRecursive.ts
  benchmark/structures/zod/ZodObjectUnionExplicit.ts
  benchmark/structures/zod/ZodObjectUnionImplicit.ts
  benchmark/structures/zod/ZodUltimateUnion.ts
  package.json
  src/programmers/AssertProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  test/features/application/test_application_array_recursive_union_explicit.ts
  test/features/assert/test_assert_array_recursive_union_explicit.ts
  test/features/is/test_is_array_recursive_union_explicit.ts
  test/features/validate/test_validate_array_recursive_union_explicit.ts
  test/structures/ArrayRecursiveUnionExplicit.ts
  tsconfig.test.json
Labels: enhancement

#231 Close #230 - how to install on `vite`
  README.md
  src/transform.ts
Labels: enhancement

#235 Fix #234 - invalid `TypeGuardError.path` bug
  package.json
  src/programmers/FeatureProgrammer.ts
  test/features/application/test_application_dynamic_array.ts
  test/features/assert/test_assert_dynamic_array.ts
  test/features/assert_equals/test_assert_equals_dynamic_array.ts
  test/features/equals/test_equals_dynamic_array.ts
  test/features/is/test_is_dynamic_array.ts
  test/features/stringify/test_stringify_dynamic_array.ts
  test/features/validate/test_validate_dynamic_array.ts
  test/features/validate_equals/test_validate_equals_dynamic_array.ts
  test/structures/DynamicArray.ts
  tsconfig.test.json
Labels: bug

#238 Close #237 - support enumeration typed property
  package.json
  src/factories/internal/emplace_metadata_object.ts
  test/features/assert/test_assert_dynamic_constant.ts
  test/features/assert/test_assert_dynamic_enumeration.ts
  test/features/assert_equals/test_assert_equals_dynamic_constant.ts
  test/features/assert_equals/test_assert_equals_dynamic_enumeration.ts
  test/features/equals/test_equals_dynamic_constant.ts
  test/features/equals/test_equals_dynamic_enumeration.ts
  test/features/is/test_is_dynamic_constant.ts
  test/features/is/test_is_dynamic_enumeration.ts
  test/features/validate/test_assert_dynamic_constant.ts
  test/features/validate/test_assert_dynamic_enumeration.ts
  test/features/validate_equals/test_validate_equals_dynamic_constant.ts
  test/features/validate_equals/test_validate_equals_dynamic_enumeration.ts
  test/issues/237.ts
  test/structures/DynamicConstant.ts
  test/structures/DynamicEnumeration.ts
Labels: enhancement

#242 Close #241 - ignore `@internal` tagged properties
  package.json
  src/factories/internal/emplace_metadata_object.ts
  test/features/application/test_application_object_internal.ts
  test/features/assert/test_assert_object_internal.ts
  test/features/assert_equals/test_assert_equals_object_internal.ts
  test/features/equals/test_equals_object_internal.ts
  test/features/is/test_is_object_internal.ts
  test/features/stringify/test_stringify_object_internal.ts
  test/features/validate/test_validate_object_internal.ts
  test/features/validate_equals/test_validate_equals_object_internal.ts
  test/structures/ObjectInternal.ts
Labels: enhancement

#253 JSON Schema | TypeBox Benchmark
  benchmark/features/benchmark_assert.ts
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_validate.ts
  benchmark/internal/AssertBenchmarker.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/AMD Ryzen 7 3700X 8-Core Processor.md
  benchmark/structures/typebox/TypeBoxArrayRecursive.ts
  benchmark/structures/typebox/TypeBoxArrayRecursiveUnionExplicit.ts
  benchmark/structures/typebox/TypeBoxArrayRecursiveUnionImplicit.ts
  benchmark/structures/typebox/TypeBoxObjectHierarchical.ts
  benchmark/structures/typebox/TypeBoxObjectRecursive.ts
  benchmark/structures/typebox/TypeBoxObjectUnionExplicit.ts
  benchmark/structures/typebox/TypeBoxObjectUnionImplicit.ts
  benchmark/structures/typebox/TypeBoxUltimateUnion.ts
  benchmark/structures/zod/ZodUltimateUnion.ts
  package.json
Labels: enhancement

#255 Develop #254 - special benchmark for `TypeBox`
  README.md
  benchmark/features/benchmark_assert.ts
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_optimizer.ts
  benchmark/features/benchmark_validate.ts
  benchmark/internal/AssertBenchmarker.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/OptimizerBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics.md
  benchmark/results/charts.xlsx
  benchmark/structures/class-validator/CvObjectUnionImplicit.ts
  benchmark/structures/io-ts/IoTsObjectUnionImplicit.ts
  benchmark/structures/typebox/TypeBoxObjectUnionImplicit.ts
  benchmark/structures/typebox/TypeBoxUltimateUnion.ts
  benchmark/structures/zod/ZodObjectUnionImplicit.ts
  benchmark/structures/zod/ZodUltimateUnion.ts
  src/module.ts
  src/transformers/CallExpressionTransformer.ts
  src/transformers/features/CreateObjectTransformer.ts
  test/features/application/ajv/test_application_ajv_object_union_implicit.ts
  test/features/application/swagger/test_application_swagger_object_union_implicit.ts
  test/features/create/test_create_array.ts
  test/features/create/test_create_object.ts
  test/issues/254.ts
  test/issues/internal/typebox.js
  test/structures/ObjectUnionImplicit.ts
Labels: enhancement

#273 Correct typo 'Undefied' to 'Undefined'
  test/features/application/ajv/test_application_ajv_object_undefined.ts
  test/features/application/swagger/test_application_swagger_object_undefined.ts
  test/features/assert/test_assert_object_undefined.ts
  test/features/assert_equals/test_assert_equals_object_undefined.ts
  test/features/assert_stringify/test_assert_stringify_object_undefined.ts
  test/features/create_assert/test_create_assert_object_undefined.ts
  test/features/create_assert_equals/test_create_assert_equals_object_undefined.ts
  test/features/create_assert_stringify/test_create_assert_stringify_object_undefined.ts
  test/features/create_equals/test_create_equals_object_undefined.ts
  test/features/create_is/test_create_is_object_undefined.ts
  test/features/create_is_stringify/test_create_is_stringify_object_undefined.ts
  test/features/create_stringify/test_create_stringify_object_undefined.ts
  test/features/create_validate/test_create_validate_object_undefined.ts
  test/features/create_validate_equals/test_create_validate_equals_object_undefined.ts
  test/features/equals/test_equals_object_undefined.ts
  test/features/is/test_is_object_undefined.ts
  test/features/is_stringify/test_is_stringify_object_undefined.ts
  test/features/stringify/test_stringify_object_undefined.ts
  test/features/validate/test_validate_object_undefined.ts
  test/features/validate_equals/test_validate_equals_object_undefined.ts
  test/structures/ObjectUndefined.ts
Labels: bug

#277 Close #268 - refactored entire benchmark program for TypeBox
  benchmark/features/benchmark_assert.ts
  benchmark/features/benchmark_assert_equals.ts
  benchmark/features/benchmark_equals.ts
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_validate.ts
  benchmark/features/benchmark_validate_equals.ts
  benchmark/index.ts
  benchmark/internal/AssertBenchmarker.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/OptimizerBenchmarker.ts
  benchmark/internal/StringifyBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/structures/ajv/AjvObjectUnionImplicit.ts
  benchmark/structures/ajv/AjvUltimateUnion.ts
  benchmark/structures/io-ts/IoTsUltimateUnion.ts
  benchmark/structures/io-ts/IoTsUtils.ts
  benchmark/structures/typebox/TypeBoxObjectUnionImplicit.ts
  benchmark/structures/typebox/TypeBoxUltimateUnion.ts
  benchmark/structures/typebox/equals/TypeBoxArrayRecursiveEquals.ts
  benchmark/structures/typebox/equals/TypeBoxArrayRecursiveUnionExplicitEquals.ts
  benchmark/structures/typebox/equals/TypeBoxArrayRecursiveUnionImplicitEquals.ts
  benchmark/structures/typebox/equals/TypeBoxObjectHierarchicalEquals.ts
  benchmark/structures/typebox/equals/TypeBoxObjectRecursiveEquals.ts
  benchmark/structures/typebox/equals/TypeBoxObjectUnionExplicitEquals.ts
  benchmark/structures/typebox/equals/TypeBoxObjectUnionImplicitEquals.ts
  benchmark/structures/typebox/equals/TypeBoxUltimateUnionEquals.ts
  benchmark/structures/zod/ZodUltimateUnion.ts
  package.json
  src/programmers/internal/application_schema.ts
  test/features/assert/test_assert_ultimate_union.ts
  test/features/is/test_is_ultimate_union.ts
  test/features/validate/test_validate_ultimate_union.ts
  test/manual.js
  test/structures/ArrayRecursive.ts
  test/structures/ArrayRecursiveUnionExplicit.ts
  test/structures/ArrayRecursiveUnionImplicit.ts
  test/structures/ObjectHierarchical.ts
  test/structures/ObjectRecursive.ts
  test/structures/ObjectUnionExplicit.ts
  test/structures/ObjectUnionImplicit.ts
  test/structures/UltimateUnion.ts
Labels: enhancement

#278 Close #276 - block duplicted checking
  src/programmers/AssertProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/ValidateProgrammer.ts
Labels: enhancement

#280 Correct several typos
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  CONTRIBUTING.md
  README.md
  src/factories/MetadataTagFactory.ts
  src/module.ts
  src/transformers/CallExpressionTransformer.ts
  src/transformers/features/AssertStringifyTransformer.ts
  test/features/application/ajv/test_application_ajv_array_union.ts
  test/features/application/swagger/test_application_swagger_array_union.ts
  test/features/assert/test_assert_array_union.ts
  test/features/assert_stringify/test_assert_stringify_array_union.ts
  test/features/create_assert/test_create_assert_array_union.ts
  test/features/create_assert_stringify/test_create_assert_stringify_array_union.ts
  test/features/create_is/test_create_is_array_union.ts
  test/features/create_is_stringify/test_create_is_stringify_array_union.ts
  test/features/create_stringify/test_create_stringify_array_union.ts
  test/features/create_validate/test_create_validate_array_union.ts
  test/features/is/test_is_array_union.ts
  test/features/is_stringify/test_is_stringify_array_union.ts
  test/features/stringify/test_stringify_array_union.ts
  test/features/validate/test_validate_array_union.ts
  test/structures/ClassNonPublic.ts
Labels: bug

#283 fix: Correct spelling and grammar mistakes in comments
  src/module.ts
Labels: bug

#285 Complement #281 - make `validate()` shorter
  benchmark/features/benchmark_TSON_iterate.ts
  benchmark/index.ts
  benchmark/internal/TsonIterateBenchmarker.ts
  src/programmers/ValidateProgrammer.ts
Labels: enhancement

#286 Complement #281 - `assertType@v3` became faster
  benchmark/features/benchmark_TSON_iterate.ts
  benchmark/features/benchmark_assert_equals_iterate.ts
  benchmark/features/benchmark_assert_equals_throw.ts
  benchmark/features/benchmark_assert_type_iterate.ts
  benchmark/features/benchmark_assert_type_throw.ts
  benchmark/features/benchmark_equals_throw.ts
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_validate.ts
  benchmark/features/benchmark_validate_equals.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/charts.xlsx
  benchmark/results/compare.md
  benchmark/structures/ajv/AjvObjectSimple.ts
  benchmark/structures/class-validator/CvObjectSimple.ts
  benchmark/structures/io-ts/IoTsObjectSimple.ts
  benchmark/structures/typebox/TypeBoxObjectSimple.ts
  benchmark/structures/typebox/equals/TypeBoxObjectSimpleEquals.ts
  benchmark/structures/zod/ZodObjectSimple.ts
  src/functional/$guard.ts
  src/module.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/AssertStringifyProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/transformers/features/AssertTransformer.ts
  src/transformers/features/CreateAssertTransformer.ts
  test/features/assert/_test_assert.ts
  test/issues/281.ts
  test/structures/ObjectSimple.ts
Labels: enhancement

#287 Benchmark #281 with my computers
  README.md
  benchmark/features/benchmark_is.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics.md
  benchmark/results/charts.xlsx
Labels: documentation, enhancement

#289 Close #288, generated functions are optimized
  README.md
  benchmark/features/benchmark_is.ts
  benchmark/features/benchmark_stringify.ts
  benchmark/index.ts
  benchmark/internal/AssertIterateBenchmarker.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/StringifyBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics.md
  benchmark/results/charts.xlsx
  package.json
  src/factories/IdentifierFactory.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/StringifyProgrammer.ts
Labels: enhancement
