Repository samchon/typia, pull requests merged in 2022-04, with the labels that each got.

#16 V2.0
  .github/workflows/build.yml
  .gitignore
  .npmignore
  README.md
  package.json
  src/factories/JsonFactory.ts
  src/factories/SchemaFactory.ts
  src/factories/TypeFactry.ts
  src/functional/argue_stringifier.ts
  src/functional/argue_stringify.ts
  src/functional/get_json_function.ts
  src/index.ts
  src/module.ts
  src/storages/JsonMemory.ts
  src/structures/IProject.ts
  src/structures/ISchema.ts
  src/transform.ts
  src/transformers/FileTransformer.ts
  src/transformers/NodeTransformer.ts
  test/features/test_stringify_array.ts
  test/features/test_stringify_array_atomic.ts
  test/features/test_stringify_array_hierarchical.ts
  test/features/test_stringify_array_recursive.ts
  test/features/test_stringify_array_tuple.ts
  test/features/test_stringify_array_union.ts
  test/features/test_stringify_atomic.ts
  test/features/test_stringify_atomic_alias.ts
  test/features/test_stringify_atomic_intersection.ts
  test/features/test_stringify_atomic_literal.ts
  test/features/test_stringify_atomic_union.ts
  test/features/test_stringify_class_closure.ts
  test/features/test_stringify_class_getter.ts
  test/features/test_stringify_class_method.ts
  test/features/test_stringify_class_public.ts
  test/features/test_stringify_complicate_union.ts
  test/features/test_stringify_object.ts
  test/features/test_stringify_object_alias.ts
  test/features/test_stringify_object_closure.ts
  test/features/test_stringify_object_intersection.ts
  test/features/test_stringify_object_nullabe.ts
  test/features/test_stringify_object_primitive.ts
  test/features/test_stringify_object_recursive.ts
  test/features/test_stringify_object_union.ts
  test/features/test_stringify_to_json_class.ts
  test/features/test_stringify_to_json_class_closure.ts
  test/features/test_stringify_to_json_object_closure.ts
  test/features/test_stringify_typeof.ts
  test/index.js
  test/index.ts
  test/internal/DynamicImportIterator.ts
  test/internal/Primitive.ts
  test/internal/RandomGenerator.ts
  test/internal/StopWatch.ts
  test/manual.js
  tsconfig.json
  tsconfig.test.json
Labels: enhancement

#18 Close #14 and Close #17
  package.json
  src/factories/FunctionFactory.ts
  src/functional/argue_stringifier.ts
  src/functional/argue_stringify.ts
  src/functional/get_json_function.ts
  src/module.ts
  src/transformers/NodeTransformer.ts
  test/features/test_stringify_atomic_implicit.ts
  test/features/test_stringify_class_closure.ts
  test/features/test_stringify_object_implicit.ts
  test/manual.js
Labels: enhancement

#22 Close #20 and Close #21
  README.md
  package.json
  src/factories/ExpressionFactory.ts
  src/factories/FunctionFactory.ts
  src/factories/JsonFactory.ts
  src/factories/MetadataFactory.ts
  src/factories/SchemaFactory.ts
  src/structures/IMetadata.ts
  src/structures/ISchema.ts
  src/structures/TypeEntry.ts
  test/features/test_stringify_object_implicit.ts
  test/features/test_stringify_object_optional.ts
  tsconfig.json
Labels: enhancement

#24 My solution for the #23
  src/factories/MetadataFactory.ts
  test/internal/RandomGenerator.ts
Labels: enhancement

#25 Refactor: no let RandomGenerator with reduce x2 faster
  test/internal/RandomGenerator.ts
Labels: enhancement, good first issue

#29 Fix #28
  package.json
  src/factories/MetadataFactory.ts
  src/factories/TypeFactry.ts
  test/features/test_stringify_class_public.ts
  test/features/test_stringify_to_json_object_closure.ts
  test/features/test_stringify_to_json_to_array..ts
  test/features/test_stringify_to_json_to_atomic.ts
  test/features/test_stringify_to_json_to_atomic_nullable.ts
  test/features/test_stringify_to_json_to_atomic_union.ts
  test/features/test_stringify_to_json_to_class_closure.ts
  test/features/test_stringify_to_json_to_complicate_union.ts
  test/features/test_stringify_to_json_to_object.ts
  test/features/test_stringify_to_json_to_object_closure.ts
  test/features/test_stringify_to_json_to_object_union.ts
Labels: bug, enhancement

#31 Close #30
  package.json
  src/factories/MetadataFactory.ts
  src/factories/SchemaFactory.ts
  src/structures/IMetadata.ts
Labels: enhancement
