Repository samchon/typia, pull requests merged in 2022-11, with the labels that each got.

#292 Enhance assert benchmark program for #290
  benchmark/features/benchmark_TSON_iterate.ts
  benchmark/features/benchmark_assert_equals_throw.ts
  benchmark/features/benchmark_assert_type_throw.ts
  benchmark/internal/AssertThrowBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics.md
  benchmark/results/charts.xlsx
  package.json
  test/structures/ArrayRecursiveUnionImplicit.ts
Labels: enhancement

#291 Correct typo 'valiation' to 'validation'
  README.md
Labels: bug

#293 Discard AssertProgrammerV2
  package.json
  src/functional/$guard.ts
  src/module.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/AssertStringifyProgrammer.ts
  src/transformers/features/AssertTransformer.ts
  src/transformers/features/CreateAssertTransformer.ts
Labels: enhancement

#296 Close #250 - support more JSON schema properties
  package.json
  src/factories/CommentFactory.ts
  src/programmers/internal/application_object.ts
  src/schemas/IJsonSchema.ts
  src/transformers/CallExpressionTransformer.ts
  test/features/application/ajv/test_application_ajv_object_json_tag.ts
  test/features/application/ajv/test_application_ajv_ultimate_union.ts
  test/features/application/swagger/test_application_swagger_object_json_tag.ts
  test/features/application/swagger/test_application_swagger_ultimate_union.ts
  test/structures/ObjectJsonTag.ts
Labels: enhancement

#299 Complement #295 - `failure` label
  README.md
  benchmark/internal/HorizontalBarChart.ts
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertType_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertType_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validate.svg
  test/issues/internal/295.svg
Labels: enhancement

#300 add benchmark
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/README.md
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/assertType_po_iterate_pc.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/assertType_po_throw_pc.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/equals.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/is.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/optimizer.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/stringify.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/validate.svg
  benchmark/results/Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz/images/validateEquals.svg
Labels: documentation, enhancement

#322 Benchmark again with release mode
  README.md
  benchmark/features/benchmark_assert_iterate.ts
  benchmark/features/benchmark_assert_throw.ts
  benchmark/index.ts
  benchmark/internal/BenchmarktReporter.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertType_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertType_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validateEquals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertType_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertType_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validateEquals.svg
  package.json
Labels: enhancement

#323 Benchmark must run on release mode
  .github/workflows/build.yml
  README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validateEquals.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertType_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertType_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validateEquals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/README.md
  package.json
  src/programmers/FeatureProgrammer.ts
Labels: enhancement

#327 Complement #325 - consider type alias generic arguments
  package.json
  src/factories/TypeFactory.ts
  test/features/application/ajv/test_application_ajv_object_generic_alias.ts
  test/features/application/ajv/test_application_ajv_object_generic_array.ts
  test/features/application/ajv/test_application_ajv_object_generic_union.ts
  test/features/application/swagger/test_application_swagger_object_generic_alias.ts
  test/features/application/swagger/test_application_swagger_object_generic_array.ts
  test/features/application/swagger/test_application_swagger_object_generic_union.ts
Labels: enhancement

#329 Fix #328 - special alias case from `nestia`
  package.json
  src/factories/MetadataCollection.ts
  src/factories/TypeFactory.ts
  test/features/application/ajv/test_application_ajv_object_generic.ts
  test/features/application/ajv/test_application_ajv_object_generic_union.ts
  test/features/application/ajv/test_application_ajv_ultimate_union.ts
  test/features/application/swagger/test_application_swagger_object_generic.ts
  test/features/application/swagger/test_application_swagger_object_generic_union.ts
  test/features/application/swagger/test_application_swagger_ultimate_union.ts
  test/issues/nestia-176.ts
Labels: bug, enhancement

#338 Benchmark #337 by AMD-5800H
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validateEquals.svg
Labels: enhancement

#340 Close #339 - default option of functional becomes `false`
  README.md
  package.json
  src/programmers/helpers/OptionPredicator.ts
  tsconfig.test.json
Labels: enhancement

#341 CPU: 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assert_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assert_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/validateEquals.svg
Labels: enhancement

#343 Close #342 - handle `Array<any>` type
  package.json
  src/programmers/CheckerProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  test/features/application/ajv/test_application_ajv_array_any.ts
  test/features/application/swagger/test_application_swagger_array_any.ts
  test/features/assert/test_assert_array_any.ts
  test/features/assert_clone/test_assert_clone_array_any.ts
  test/features/assert_equals/test_assert_equals_array_any.ts
  test/features/assert_stringify/test_assert_stringify_array_any.ts
  test/features/assert_type/test_assert__type_array_any.ts
  test/features/clone/test_clone_array_any.ts
  test/features/create_assert/test_create_assert_array_any.ts
  test/features/create_assert_clone/test_create_assert_clone_array_any.ts
  test/features/create_assert_equals/test_create_assert_equals_array_any.ts
  test/features/create_assert_stringify/test_create_assert_stringify_array_any.ts
  test/features/create_assert_type/test_create_assert_type_array_any.ts
  test/features/create_clone/test_create_clone_array_any.ts
  test/features/create_equals/test_create_equals_array_any.ts
  test/features/create_is/test_create_is_array_any.ts
  test/features/create_is_clone/test_create_is_clone_array_any.ts
  test/features/create_is_stringify/test_create_is_stringify_array_any.ts
  test/features/create_stringify/test_create_stringify_array_any.ts
  test/features/create_validate/test_create_validate_array_any.ts
  test/features/create_validate_equals/test_create_validate_equals_array_any.ts
  test/features/equals/test_equals_array_any.ts
  test/features/is/test_is_array_any.ts
  test/features/is_clone/test_is_clone_array_any.ts
  test/features/is_stringify/test_is_stringify_array_any.ts
  test/features/stringify/test_stringify_array_any.ts
  test/features/validate/test_validate_array_any.ts
  test/features/validate_equals/test_validate_equals_array_any.ts
  test/issues/342.ts
  test/structures/ArrayAny.ts
Labels: enhancement

#348 Change units of benchmark result tables
  benchmark/features/benchmark_optimizer.ts
  benchmark/features/benchmark_stringify.ts
  benchmark/index.js
  benchmark/internal/AssertIterateBenchmarker.ts
  benchmark/internal/AssertThrowBenchmarker.ts
  benchmark/internal/BenchmarktReporter.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/OptimizerBenchmarker.ts
  benchmark/internal/StringifyBenchmarker.ts
  benchmark/internal/ValidateBenchmarker.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validateEquals.svg
Labels: enhancement

#350 Fix #346 - primitive like interface type
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/factories/TypeFactory.ts
  src/factories/internal/iterate_metadata.ts
  src/factories/internal/iterate_metadata_atomic.ts
  test/issues/346.ts
  test/issues/347.ts
Labels: bug, enhancement

#353 Develop #352 - enhance `IValidation` type
  package.json
  src/IValidation.ts
  src/module.ts
  src/programmers/ValidateProgrammer.ts
  test/features/validate/_test_validate.ts
Labels: enhancement

#357 Close #356 - optimize `TSON.stringify()` function by inlining
  benchmark/features/benchmark_stringify.ts
  benchmark/features/benchmark_stringify_server.ts
  benchmark/index.ts
  benchmark/internal/BenchmarktReporter.ts
  benchmark/internal/ServerBenchmarker.ts
  benchmark/internal/StringifyBenchmarker.ts
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/assert_po_throw_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/stringify_po_server_pc.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/validateEquals.svg
  benchmark/servers/ServerStorage.ts
  benchmark/servers/stringify/express_assert_stringify.ts
  benchmark/servers/stringify/express_is_stringify.ts
  benchmark/servers/stringify/express_pure.ts
  benchmark/servers/stringify/express_stringify.ts
  benchmark/servers/stringify/fastify.ts
  benchmark/servers/stringify/index.ts
  benchmark/structures/typebox/TypeBoxArrayHierarchical.ts
  benchmark/structures/typebox/TypeBoxArraySimple.ts
  package.json
  src/programmers/IsProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/helpers/StringifyJoinder.ts
  test/issues/500.ts
  test/structures/ArrayHierarchical.ts
  test/structures/ArraySimple.ts
Labels: enhancement

#360 Complement #344 - `IValidatin.ISuccess<T>.data`
  src/IValidation.ts
  src/functional/$report.ts
  src/programmers/ValidateProgrammer.ts
Labels: enhancement

#365 Benchmark Surfae Pro 8
  benchmark/index.ts
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify_po_server_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validateEquals.svg
Labels: enhancement

#366 Optimize `equals()` and related functions
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assert_po_iterate_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/assert_po_throw_pc.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/equals.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/validate.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz/images/validateEquals.svg
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 5800H with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assert_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assert_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validateEquals.svg
  benchmark/results/Apple M1 Max/README.md
  benchmark/results/Apple M1 Max/images/assertEquals_po_iterate_pc.svg
  benchmark/results/Apple M1 Max/images/assertEquals_po_throw_pc.svg
  benchmark/results/Apple M1 Max/images/assert_po_iterate_pc.svg
  benchmark/results/Apple M1 Max/images/assert_po_throw_pc.svg
  benchmark/results/Apple M1 Max/images/equals.svg
  benchmark/results/Apple M1 Max/images/is.svg
  benchmark/results/Apple M1 Max/images/optimizer.svg
  benchmark/results/Apple M1 Max/images/stringify.svg
  benchmark/results/Apple M1 Max/images/validate.svg
  benchmark/results/Apple M1 Max/images/validateEquals.svg
  benchmark/results/Apple M1/README.md
  benchmark/results/Apple M1/images/assertEquals_po_iterate_pc.svg
  benchmark/results/Apple M1/images/assertEquals_po_throw_pc.svg
  benchmark/results/Apple M1/images/assert_po_iterate_pc.svg
  benchmark/results/Apple M1/images/assert_po_throw_pc.svg
  benchmark/results/Apple M1/images/equals.svg
  benchmark/results/Apple M1/images/is.svg
  benchmark/results/Apple M1/images/optimizer.svg
  benchmark/results/Apple M1/images/stringify.svg
  benchmark/results/Apple M1/images/validate.svg
  benchmark/results/Apple M1/images/validateEquals.svg
  package.json
  src/programmers/internal/check_dynamic_properties.ts
Labels: enhancement

#367 Benchmark `equals()` on SP8
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/equals.svg
Labels: enhancement

#368 Benchmark `equals()` on AMD-5900HX
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assertEquals_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assert_po_iterate_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/assert_po_throw_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/equals.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/stringify_po_server_pc.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validate.svg
  benchmark/results/AMD Ryzen 9 5900HX with Radeon Graphics/images/validateEquals.svg
Labels: enhancement

#370 Fix #369 - empty tuple and object literal types
  src/IValidation.ts
  src/factories/TypeFactory.ts
  src/factories/internal/iterate_metadata.ts
  src/module.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  test/features/application/ajv/test_application_ajv_object_undefined.ts
  test/features/application/swagger/test_application_swagger_object_undefined.ts
  test/features/validate/_test_validate.ts
  test/features/validate_equals/_test_validate_equals.ts
  test/issues/369.ts
  test/structures/ObjectUndefined.ts
Labels: enhancement

#374 Fix #371 and Fix #373 - functional property case
  package.json
  src/programmers/CheckerProgrammer.ts
  test/issues/373.ts
Labels: bug, enhancement

#379 Fix #378 - special case of `functional: false`
  package.json
  src/programmers/CheckerProgrammer.ts
  test/issues/378.ts
Labels: bug, enhancement

#381 Add Protocol Buffers related function
  src/functional/$proto_bytes.ts
  src/functional/$proto_field.ts
  src/functional/$proto_float.ts
  src/functional/$proto_i32.ts
  src/functional/$proto_i64.ts
  src/functional/$proto_size.ts
  src/functional/$proto_string.ts
  src/functional/$varint.ts
  src/functional/$zigzag.ts
  test/features/protoify/test_$proto_size_varint.ts
  test/internal/Hex.ts
  test/testdata/proto_ObjectSimple.proto
  test/testdata/proto_ObjectSimple.protoscope
  test/testdata/proto_ObjectSimple.protoscope.bin
  test/testdata/proto_ObjectSimple.ts
  test/testdata/proto_i64.protoscope
  test/testdata/proto_i64.protoscope.bin
  test/testdata/proto_packed_varint.protoscope
  test/testdata/proto_packed_varint.protoscope.bin
Labels: enhancement

#385 Fixing #351 - stop using TS 4.9 for a while
  package.json
  src/programmers/internal/application_number.ts
  src/schemas/IJsonSchema.ts
  test/features/application/ajv/test_application_ajv_TagStep.ts
  test/features/application/ajv/test_application_ajv_UltimateUnion.ts
  test/features/application/replace.js
  test/features/application/swagger/test_application_swagger_TagStep.ts
  test/features/application/swagger/test_application_swagger_UltimateUnion.ts
Labels: bug
