Repository samchon/typia, pull requests merged in 2022-09, with the labels that each got.

#176 benchmark: specify type to avoid TSError
  benchmark/internal/AssertBenchmarker.ts
  benchmark/internal/IsBenchmarker.ts
  benchmark/internal/OptimizerBenchmarker.ts
  benchmark/internal/StringifyBenchmarker.ts
Labels: bug, enhancement

#179 Edit README, add array tags
  README.md
Labels: documentation

#182 Close #181, tag related properties on `Metadata` and `IJsonSchema`
  package.json
  src/factories/MetadataCollection.ts
  src/factories/MetadataFactory.ts
  src/metadata/IJsDocTagInfo.ts
  src/metadata/IMetadataObject.ts
  src/metadata/IMetadataProperty.ts
  src/metadata/MetadataObject.ts
  src/metadata/MetadataProperty.ts
  src/programmers/ApplicationProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/schemas/IJsonComponents.ts
  src/schemas/IJsonSchema.ts
  test/features/application/_test_application.ts
  test/features/application/test_application_array_hierarchical.ts
  test/features/application/test_application_array_recursive.ts
  test/features/application/test_application_array_recursive_union_explicit.ts
  test/features/application/test_application_array_recursive_union_implicit.ts
  test/features/application/test_application_array_simple.ts
  test/features/application/test_application_class_closure.ts
  test/features/application/test_application_class_getter.ts
  test/features/application/test_application_class_method.ts
  test/features/application/test_application_class_non_public.ts
  test/features/application/test_application_class_property_assignment.ts
  test/features/application/test_application_constant_atomic_union.ts
  test/features/application/test_application_constant_atomic_wrapper.ts
  test/features/application/test_application_namespace.ts
  test/features/application/test_application_object_alias.ts
  test/features/application/test_application_object_closure.ts
  test/features/application/test_application_object_generic.ts
  test/features/application/test_application_object_generic_alias.ts
  test/features/application/test_application_object_generic_array.ts
  test/features/application/test_application_object_generic_union.ts
  test/features/application/test_application_object_intersection.ts
  test/features/application/test_application_object_literal_property.ts
  test/features/application/test_application_object_literal_type.ts
  test/features/application/test_application_object_nullable.ts
  test/features/application/test_application_object_primitive.ts
  test/features/application/test_application_object_recursive.ts
  test/features/application/test_application_object_simple.ts
  test/features/application/test_application_object_undefined.ts
  test/features/application/test_application_object_union_implicit.ts
  test/features/application/test_application_tag_array.ts
  test/features/application/test_application_tag_atomic_union.ts
  test/features/application/test_application_tag_format.ts
  test/features/application/test_application_tag_length.ts
  test/features/application/test_application_tag_matrix.ts
  test/features/application/test_application_tag_object_union.ts
  test/features/application/test_application_tag_pattern.ts
  test/features/application/test_application_tag_range.ts
  test/features/application/test_application_tag_tuple.ts
  test/features/application/test_application_tag_type.ts
  test/features/application/test_application_ultimate_union.ts
Labels: enhancement

#183 Close #180, add more validation tags
  README.md
  package.json
  src/factories/MetadataTagFactory.ts
  src/metadata/IMetadataTag.ts
  src/programmers/internal/check_number.ts
  test/features/application/test_application_tag_step.ts
  test/features/application/test_application_ultimate_union.ts
  test/features/assert/test_assert_tag_step.ts
  test/features/is/test_is_tag_step.ts
  test/features/stringify/test_stringify_tag_step.ts
  test/features/validate/test_validate_tag_step.ts
  test/structures/TagStep.ts
Labels: enhancement

#185 Fix #184, validators support unknown type
  package.json
  src/module.ts
  test/issues/184.ts
Labels: bug, enhancement

#189 Fix #188, mis-typed `$$tail`
  package.json
  src/programmers/helpers/StringifyJoinder.ts
Labels: bug

#192 Fix #191 - index identifier not by random generator but by sequential…
  package.json
  src/programmers/CheckerProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/helpers/FunctionImporeter.ts
Labels: bug

#194 Test #193, when all properties are optional
  test/features/application/test_application_object_optional.ts
  test/features/assert/test_assert_object_optional.ts
  test/features/is/test_is_object_optional.ts
  test/features/stringify/test_stringify_object_optional.ts
  test/features/validate/test_validate_object_optional.ts
  test/structures/ObjectOptional.ts
Labels: help wanted, invalid

#198 Fix #197 - no superfluous property inspection when `undefined` value comes
  package.json
  src/programmers/internal/check_object.ts
  src/programmers/internal/check_properties.ts
Labels: bug, enhancement

#201 Close #200, refactor `MetadataProperty` for dynamic properties
  package.json
  src/factories/MetadataFactory.ts
  src/factories/internal/MetadataHelper.ts
  src/metadata/IMetadataProperty.ts
  src/metadata/Metadata.ts
  src/metadata/MetadataObject.ts
  src/metadata/MetadataProperty.ts
  src/programmers/ApplicationProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/helpers/IExpressionEntry.ts
  src/programmers/helpers/StringifyJoinder.ts
  src/programmers/helpers/UnionExplorer.ts
  src/programmers/helpers/UnionPredicator.ts
  src/programmers/internal/check_properties.ts
  test/internal/RandomGenerator.ts
  test/structures/ObjectDynamic.ts
Labels: enhancement

#204 Fix #203 - export `IValidation`
  package.json
  src/module.ts
  src/schemas/IJsonSchema.ts
  src/schemas/JsonTypeChecker.ts
  test/issues/202.ts
Labels: enhancement

#207 Close #206 - separate `MetadataFactory`
  package.json
  src/factories/MetadataFactory.ts
  src/factories/internal/emplace_metadata_object.ts
  src/factories/internal/explore_metadata.ts
  src/factories/internal/iterate_metadata.ts
  src/factories/internal/iterate_metadata_array.ts
  src/factories/internal/iterate_metadata_atomic.ts
  src/factories/internal/iterate_metadata_coalesce.ts
  src/factories/internal/iterate_metadata_constant.ts
  src/factories/internal/iterate_metadata_object.ts
  src/factories/internal/iterate_metadata_resolve.ts
  src/factories/internal/iterate_metadata_tuple.ts
  src/factories/internal/iterate_metadata_union.ts
Labels: enhancement

#209 Close #208 - `Metadata.templates`
  package.json
  src/factories/internal/iterate_metadata.ts
  src/factories/internal/iterate_metadata_template.ts
  src/metadata/IMetadata.ts
  src/metadata/Metadata.ts
  src/programmers/ApplicationProgrammer.ts
Labels: enhancement

#210 Close #205, support template literal types
  README.md
  package.json
  src/factories/internal/explore_metadata.ts
  src/metadata/Metadata.ts
  src/programmers/ApplicationProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/internal/check_string.ts
  src/programmers/internal/check_string_tags.ts
  src/programmers/internal/check_template.ts
  src/programmers/internal/template_to_pattern.ts
  src/utils/ArrayUtil.ts
  test/features/application/test_application_array_recursive_union_explicit.ts
  test/features/application/test_application_array_recursive_union_implicit.ts
  test/features/application/test_application_object_generic_union.ts
  test/features/application/test_application_object_nullable.ts
  test/features/application/test_application_tag_object_union.ts
  test/features/application/test_application_template_atomic.ts
  test/features/application/test_application_template_constant.ts
  test/features/application/test_application_template_union.ts
  test/features/application/test_application_ultimate_union.ts
  test/features/assert/test_assert_template_atomic.ts
  test/features/assert/test_assert_template_constant.ts
  test/features/assert/test_assert_template_union.ts
  test/features/assert_equals/test_assert_equals_template_atomic.ts
  test/features/assert_equals/test_assert_equals_template_constant.ts
  test/features/assert_equals/test_assert_equals_template_union.ts
  test/features/equals/test_equals_template_atomic.ts
  test/features/equals/test_equals_template_constant.ts
  test/features/equals/test_equals_template_union.ts
  test/features/is/test_is_template_atomic.ts
  test/features/is/test_is_template_constant.ts
  test/features/is/test_is_template_union.ts
  test/features/stringify/test_stringify_template_atomic.ts
  test/features/stringify/test_stringify_template_constant.ts
  test/features/stringify/test_stringify_template_union.ts
  test/features/validate/test_validate_template_atomic.ts
  test/features/validate/test_validate_template_constant.ts
  test/features/validate/test_validate_template_union.ts
  test/features/validate_equals/test_validate_equals_template_atomic.ts
  test/features/validate_equals/test_validate_equals_template_constant.ts
  test/features/validate_equals/test_validate_equals_template_union.ts
  test/manual.js
  test/structures/TemplateAtomic.ts
  test/structures/TemplateConstant.ts
  test/structures/TemplateUnion.ts
Labels: enhancement
