Repository samchon/typia, pull requests merged in 2023-03, with the labels that each got.

#539 Fix #537 - when same named interface and class come
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/factories/internal/metadata/emplace_metadata_object.ts
  test/issues/537.ts
  test/issues/999.ts
Labels: bug, enhancement

#541 Fix #540 - support every uuid versions
  package.json
  packages/typescript-json/package.json
  src/functional/$is_uuid.ts
  test/issues/540.ts
Labels: bug

#542 Complement #540 - more exact uuid validation regex
  package.json
  packages/typescript-json/package.json
  src/functional/$is_uuid.ts
  test/issues/540.ts
Labels: enhancement

#546 Fix #544 - wrong `IJsonSchema.maximum` condition
  package.json
  src/programmers/internal/application_number.ts
  test/issues/544.ts
Labels: bug

#547 Fix #545 - Generic specification in header
  src/module.ts
Labels: bug

#549 Fix #548 - `IJsonSchema.INumeric.exclusiveMinimum` is `boolean` type
  package.json
  packages/typescript-json/package.json
  src/programmers/internal/application_number.ts
  src/schemas/IJsonSchema.ts
  test/generated/output/assert/test_assert_UltimateUnion.ts
  test/generated/output/assertClone/test_assertClone_UltimateUnion.ts
  test/generated/output/assertParse/test_assertParse_UltimateUnion.ts
  test/generated/output/assertStringify/test_assertStringify_UltimateUnion.ts
  test/generated/output/clone/test_clone_UltimateUnion.ts
  test/generated/output/createAssert/test_createAssert_UltimateUnion.ts
  test/generated/output/createAssertClone/test_createAssertClone_UltimateUnion.ts
  test/generated/output/createAssertParse/test_createAssertParse_UltimateUnion.ts
  test/generated/output/createAssertStringify/test_createAssertStringify_UltimateUnion.ts
  test/generated/output/createClone/test_createClone_UltimateUnion.ts
  test/generated/output/createIs/test_createIs_UltimateUnion.ts
  test/generated/output/createIsClone/test_createIsClone_UltimateUnion.ts
  test/generated/output/createIsParse/test_createIsParse_UltimateUnion.ts
  test/generated/output/createIsStringify/test_createIsStringify_UltimateUnion.ts
  test/generated/output/createStringify/test_createStringify_UltimateUnion.ts
  test/generated/output/createValidate/test_createValidate_UltimateUnion.ts
  test/generated/output/createValidateClone/test_createValidateClone_UltimateUnion.ts
  test/generated/output/createValidateParse/test_createValidateParse_UltimateUnion.ts
  test/generated/output/createValidateStringify/test_createValidateStringify_UltimateUnion.ts
  test/generated/output/is/test_is_UltimateUnion.ts
  test/generated/output/isClone/test_isClone_UltimateUnion.ts
  test/generated/output/isParse/test_isParse_UltimateUnion.ts
  test/generated/output/isStringify/test_isStringify_UltimateUnion.ts
  test/generated/output/stringify/test_stringify_UltimateUnion.ts
  test/generated/output/validate/test_validate_UltimateUnion.ts
  test/generated/output/validateClone/test_validateClone_UltimateUnion.ts
  test/generated/output/validateParse/test_validateParse_UltimateUnion.ts
  test/generated/output/validateStringify/test_validateStringify_UltimateUnion.ts
  test/schemas/json/ajv/TagRange.json
  test/schemas/json/ajv/TagStep.json
  test/schemas/json/ajv/UltimateUnion.json
  test/schemas/json/swagger/TagRange.json
  test/schemas/json/swagger/TagStep.json
  test/schemas/json/swagger/UltimateUnion.json
Labels: bug

#555 Fix samchon/nestia#282 - too long type name
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  src/factories/TypeFactory.ts
  src/transformers/features/miscellaneous/CreateRandomGenerator.ts
  src/transformers/features/miscellaneous/RandomTransformer.ts
  src/transformers/internal/GenericTransformer.ts
  test/issues/input/nestia-282.ts
  test/issues/output/532.ts
  test/issues/output/nestia-282.ts
Labels: bug

#558 typo "typescript"
  README.md
Labels: bug, documentation

#566 Fix #557 - infinite generation when nested output path
  package.json
  packages/typescript-json/package.json
  src/factories/TypiaFileFactory.ts
  test/issues/generate/532.ts
  test/issues/generate/nestia-282.ts
  test/issues/generate/output/532.ts
  test/issues/generate/output/nestia-282.ts
  test/issues/output/532.ts
  test/issues/output/nestia-282.ts
Labels: bug
