Repository samchon/typia, pull requests merged in 2023-07, with the labels that each got.

#705 Fix #704 - comment tags when repeated type comes
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/factories/internal/metadata/emplace_metadata_object.ts
  src/factories/internal/metadata/iterate_metadata_collection.ts
  src/factories/internal/metadata/iterate_metadata_tag.ts
  src/metadata/MetadataObject.ts
  test/issues/704.js
  test/issues/704.ts
  website/build/raw.js
  website/package-lock.json
  website/package.json
  website/public/sitemap-0.xml
  website/src/utils/Compiler.ts
Labels: bug, enhancement

#707 Fix #706 - support `exactOptionalPropertyTypes` option
  build/test.ts
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/emplace_metadata_object.ts
  src/factories/internal/metadata/emplace_metadata_tuple.ts
  src/metadata/Metadata.ts
  src/metadata/MetadataObject.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/helpers/StringifyJoinder.ts
  src/programmers/helpers/StringifyPredicator.ts
  src/programmers/helpers/UnionPredicator.ts
  src/programmers/internal/application_object.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/stringify_regular_properties.ts
  test/tsconfig.issue.json
  website/package-lock.json
  website/package.json
  website/public/sitemap-0.xml
Labels: bug, enhancement

#698 Make literals work with null
  src/module.ts
  src/programmers/LiteralsProgrammer.ts
  test/features/literals/test_literals_WithNull.ts
  test/features/literals/test_literals_WithStrings.ts
  test/internal/_test_literals.ts
Labels: invalid, question

#711 Add `package` word on reserved keywords.
  package.json
  packages/typescript-json/package.json
  src/utils/Escaper.ts
Labels: bug, enhancement

#713 Exact swagger generation for alias types.
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataCollection.ts
  src/factories/internal/metadata/emplace_metadata_alias.ts
  src/factories/internal/metadata/iterate_metadata_alias.ts
  src/factories/internal/metadata/iterate_metadata_collection.ts
  src/metadata/IMetadataAlias.ts
  src/metadata/MetadataAlias.ts
  src/programmers/LiteralsProgrammer.ts
  src/programmers/internal/application_alias.ts
  src/programmers/internal/application_object.ts
  test/features/literals/test_literals_WithNull.ts
  test/features/literals/test_literals_WithStrings.ts
  test/generated/output/literals/test_literals_WithNull.ts
  test/generated/output/literals/test_literals_WithStrings.ts
  test/internal/_test_literals.ts
  test/issues/literals.ts
  test/issues/tag.ts
Labels: bug, enhancement

#720 Fix #719 - `stringify()` when any typed property
  package.json
  packages/typescript-json/package.json
  src/metadata/Metadata.ts
  test/issues/stringify-any.ts
Labels: bug

#723 Benchmark on AMD 6800HS
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/README.md
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/assert-error.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/assert.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/is.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/optimizer.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/server-assert.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/server-performance.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/server-stringify.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/stringify.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/validate-error.svg
  benchmark/results/AMD Ryzen 7 6800HS with Radeon Graphics/images/validate.svg
Labels: documentation

#722 Benchmark on AMD EPYC 7763
  benchmark/results/AMD EPYC 7763 64-Core Processor/README.md
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/assert-error.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/assert.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/is.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/optimizer.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/server-assert.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/server-performance.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/server-stringify.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/stringify.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/validate-error.svg
  benchmark/results/AMD EPYC 7763 64-Core Processor/images/validate.svg
Labels: documentation, enhancement

#727 Complement #726 - much more exact comments analyzing
  package.json
  packages/typescript-json/package.json
  src/factories/CommentFactory.ts
  test/issues/comment.ts
  test/schemas/json/ajv/ObjectJsonTag.json
  test/schemas/json/ajv/TagArray.json
  test/schemas/json/ajv/TagAtomicUnion.json
  test/schemas/json/ajv/TagCustom.json
  test/schemas/json/ajv/TagDefault.json
  test/schemas/json/ajv/TagFormat.json
  test/schemas/json/ajv/TagLength.json
  test/schemas/json/ajv/TagMatrix.json
  test/schemas/json/ajv/TagObjectUnion.json
  test/schemas/json/ajv/TagRange.json
  test/schemas/json/ajv/TagStep.json
  test/schemas/json/ajv/TagTuple.json
  test/schemas/json/ajv/TagType.json
  test/schemas/json/ajv/UltimateUnion.json
  test/schemas/json/swagger/ObjectJsonTag.json
  test/schemas/json/swagger/TagArray.json
  test/schemas/json/swagger/TagAtomicUnion.json
  test/schemas/json/swagger/TagCustom.json
  test/schemas/json/swagger/TagDefault.json
  test/schemas/json/swagger/TagFormat.json
  test/schemas/json/swagger/TagLength.json
  test/schemas/json/swagger/TagMatrix.json
  test/schemas/json/swagger/TagObjectUnion.json
  test/schemas/json/swagger/TagRange.json
  test/schemas/json/swagger/TagStep.json
  test/schemas/json/swagger/TagTuple.json
  test/schemas/json/swagger/TagType.json
  test/schemas/json/swagger/UltimateUnion.json
Labels: enhancement

#728 Complement #726 - `JSDocParameterTag` case.
  package.json
  packages/typescript-json/package.json
  src/factories/CommentFactory.ts
  test/issues/comment-function.ts
Labels: bug, enhancement

#730 Close #729 - `@hidden` tag for JSON schema
  package.json
  packages/typescript-json/package.json
  src/programmers/internal/application_object.ts
  test/features/issues/test_issue_hidden_comment_tag.ts
  test/generated/output/issues/test_issue_hidden_comment_tag.ts
  test/issues/hidden.ts
  website/package-lock.json
  website/package.json
  website/pages/docs/json/schema.mdx
  website/public/sitemap-0.xml
Labels: documentation, enhancement
