Repository samchon/typia, pull requests merged in 2023-10, with the labels that each got.

#833 Fix #831 - exact optional type analyzing.
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/emplace_metadata_object.ts
  test/features/issues/test_issue_831_optional.ts
  test/generated/output/issues/test_issue_831_optional.ts
  test/issues/swagger.ts
  test/schemas/json/ajv/DynamicEnumeration.json
  test/schemas/json/swagger/DynamicEnumeration.json
Labels: bug, enhancement

#839 Close #838 - show typia version on playground.
  website/public/sitemap-0.xml
  website/src/components/OutputViewer.tsx
  website/src/utils/Singleton.ts
Labels: documentation

#840 Ban `yarn berry` on setup wizard.
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
Labels: bug, documentation, enhancement

#846 Remove deprecated @types/commander package
  package.json
Labels: enhancement

#847 Print CLI output when running `npx typia setup`.
  package.json
  packages/typescript-json/package.json
  src/executable/setup/CommandExecutor.ts
Labels: enhancement

#851 Pending TypeScript v5.3 update.
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  website/package.json
Labels: bug, enhancement
