Repository samchon/typia, pull requests merged in 2023-04, with the labels that each got.

#569 Complement #560 - determine custom validator spec
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/CustomValidatorMap.ts
  src/functional/$dictionary.ts
  src/functional/$is_custom.ts
  src/module.ts
  test/structures/TagCustom.ts
Labels: enhancement

#576 Close #575 - new function `literals()`
  package.json
  src/module.ts
  src/programmers/LiteralsProgrammer.ts
  src/transformers/CallExpressionTransformer.ts
  src/transformers/features/miscellaneous/ApplicationTransformer.ts
  src/transformers/features/miscellaneous/CreateRandomTransformer.ts
  src/transformers/features/miscellaneous/LiteralsTransformer.ts
  src/transformers/features/miscellaneous/MetadataTransformer.ts
  src/transformers/features/miscellaneous/RandomTransformer.ts
  test/features/literals/test_literals_constants.ts
  test/features/literals/test_literals_enumeration.ts
  test/index.ts
Labels: enhancement

#577 Fix #573 - exact import path generation
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/transformers/ImportTransformer.ts
  test/issues/generate/532.ts
  test/issues/generate/573.ts
  test/issues/generate/575.ts
  test/issues/generate/input/532.ts
  test/issues/generate/input/573.ts
  test/issues/generate/input/575.ts
  test/issues/generate/input/nestia-282.ts
  test/issues/generate/nestia-282.ts
  test/issues/generate/output/532.ts
  test/issues/generate/output/nestia-282.ts
  test/issues/generate/structures/ISomeOutputDto.ts
Labels: bug

#582 Fix #573 - unable to run setup on Macbook + `pnpm`
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/executable/TypiaGenerateWizard.ts
  src/executable/TypiaSetupWizard.ts
  src/executable/setup/ArgumentParser.ts
  src/executable/setup/CommandExecutor.ts
  src/executable/setup/FileRetriever.ts
  src/executable/setup/PackageManager.ts
  src/executable/setup/PluginConfigurator.ts
  src/executable/typia.ts
Labels: bug, enhancement

#586 Fix #552
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  src/factories/TypiaFileFactory.ts
Labels: bug, enhancement, good first issue

#589 Close #588 - make README concise
  README.md
Labels: documentation, enhancement

#593 Advanced `npx typia setup` command
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  src/executable/setup/PackageManager.ts
Labels: enhancement

#596 Close #595 - `docs` directory in the `master` branch
  docs/.gitignore
  docs/deploy.js
  docs/next-env.d.ts
  docs/next.config.js
  docs/package.json
  docs/pages/_meta.json
  docs/pages/docs/__templates/import.txt
  docs/pages/docs/__templates/tab-aot.txt
  docs/pages/docs/__templates/tab-module.txt
  docs/pages/docs/_meta.json
  docs/pages/docs/index.mdx
  docs/pages/docs/json/_meta.json
  docs/pages/docs/json/parse.mdx
  docs/pages/docs/json/schema.mdx
  docs/pages/docs/json/stringify.mdx
  docs/pages/docs/random.mdx
  docs/pages/docs/setup.mdx
  docs/pages/docs/utilization/_meta.json
  docs/pages/docs/utilization/nestjs.mdx
  docs/pages/docs/utilization/trpc.mdx
  docs/pages/docs/validators/_meta.json
  docs/pages/docs/validators/assert.mdx
  docs/pages/docs/validators/comment-tags.mdx
  docs/pages/docs/validators/is.mdx
  docs/pages/docs/validators/validate.mdx
  docs/pages/index.mdx
  docs/public/.nojekyll
  docs/public/CNAME
  docs/public/favicon/android-chrome-192x192.png
  docs/public/favicon/android-chrome-512x512.png
  docs/public/favicon/apple-touch-icon.png
  docs/public/favicon/favicon-16x16.png
  docs/public/favicon/favicon-32x32.png
  docs/public/favicon/favicon.ico
  docs/public/favicon/site.webmanifest
  docs/public/logo.png
  docs/public/og.jpg
  docs/theme.config.tsx
  docs/tsconfig.json
Labels: documentation, enhancement

#597 Add MS clarity (something like GA)
  .eslintrc.cjs
  .vscode/settings.json
  docs/pages/_app.js
  docs/pages/docs/validators/assert.mdx
  docs/pages/docs/validators/is.mdx
  docs/pages/docs/validators/validate.mdx
  docs/theme.config.tsx
  package.json
Labels: enhancement

#606 Fix #603 - emtpy tuple in object literal expression
  src/factories/internal/metadata/iterate_metadata.ts
  test/issues/603.ts
Labels: bug

#608 Fix #607 - let `typia.prune<T>()` to support `Record<string, T>` type
  src/programmers/helpers/PruneJoiner.ts
  test/generated/output/assertPrune/test_assertPrune_DynamicComposite.ts
  test/generated/output/assertPrune/test_assertPrune_DynamicTemplate.ts
  test/generated/output/assertPrune/test_assertPrune_DynamicUnion.ts
  test/generated/output/createAssertPrune/test_createAssertPrune_DynamicComposite.ts
  test/generated/output/createAssertPrune/test_createAssertPrune_DynamicTemplate.ts
  test/generated/output/createAssertPrune/test_createAssertPrune_DynamicUnion.ts
  test/generated/output/createIsPrune/test_createIsPrune_DynamicComposite.ts
  test/generated/output/createIsPrune/test_createIsPrune_DynamicTemplate.ts
  test/generated/output/createIsPrune/test_createIsPrune_DynamicUnion.ts
  test/generated/output/createPrune/test_createPrune_DynamicComposite.ts
  test/generated/output/createPrune/test_createPrune_DynamicTemplate.ts
  test/generated/output/createPrune/test_createPrune_DynamicUnion.ts
  test/generated/output/createValidatePrune/test_createValidatePrune_DynamicComposite.ts
  test/generated/output/createValidatePrune/test_createValidatePrune_DynamicTemplate.ts
  test/generated/output/createValidatePrune/test_createValidatePrune_DynamicUnion.ts
  test/generated/output/isPrune/test_isPrune_DynamicComposite.ts
  test/generated/output/isPrune/test_isPrune_DynamicTemplate.ts
  test/generated/output/isPrune/test_isPrune_DynamicUnion.ts
  test/generated/output/prune/test_prune_DynamicComposite.ts
  test/generated/output/prune/test_prune_DynamicTemplate.ts
  test/generated/output/prune/test_prune_DynamicUnion.ts
  test/generated/output/validatePrune/test_validatePrune_DynamicComposite.ts
  test/generated/output/validatePrune/test_validatePrune_DynamicTemplate.ts
  test/generated/output/validatePrune/test_validatePrune_DynamicUnion.ts
  test/issues/generate/573.ts
  test/issues/generate/575.ts
  test/issues/generate/input/prune.ts
  test/issues/generate/nestia-282.ts
  test/issues/generate/prune.ts
  website/pages/docs/json/schema.mdx
Labels: bug, enhancement

#585 Support TypeScript v5
  README.md
  benchmark/internal/HorizontalBarChart.ts
  build/publish.ts
  build/tsconfig.json
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  src/executable/typia.ts
  src/factories/IdentifierFactory.ts
  src/metadata/MetadataConstant.ts
  src/programmers/CheckerProgrammer.ts
  test/issue.js
  test/tsconfig.issue.json
Labels: documentation, enhancement

#615 Setup wizard to configure `strictNullChecks: true`
  package.json
  packages/typescript-json/package.json
  src/executable/setup/PluginConfigurator.ts
Labels: enhancement

#616 Use proper vite configuration
  website/pages/docs/setup.mdx
Labels: documentation, good first issue
