Repository samchon/typia, pull requests merged in 2023-06, with the labels that each got.

#643 Support JsDoc `type` tag like `@type {int}`
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataTagFactory.ts
  src/programmers/internal/application_number.ts
  test/issues/tag.ts
Labels: enhancement

#651 Enforce `strictNullChecks` to be true
  package.json
  packages/typescript-json/package.json
  src/transform.ts
Labels: enhancement

#658 Upgrade peerDependencies of TypeScript
  package.json
  packages/typescript-json/package.json
Labels: enhancement

#659 Enhance `Object.toJSON()` type.
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/emend_metadata_atomics.ts
  src/factories/internal/metadata/explore_metadata.ts
  src/factories/internal/metadata/iterate_metadata.ts
  src/factories/internal/metadata/iterate_metadata_resolve.ts
  src/factories/internal/metadata/iterate_metadata_union.ts
  src/programmers/StringifyProgrammer.ts
  test/generated/output/assertClone/test_assertClone_NativeUnion.ts
  test/generated/output/assertClone/test_assertClone_ToJsonUnion.ts
  test/generated/output/assertStringify/test_assertStringify_ToJsonDouble.ts
  test/generated/output/assertStringify/test_assertStringify_ToJsonTuple.ts
  test/generated/output/assertStringify/test_assertStringify_ToJsonUnion.ts
  test/generated/output/clone/test_clone_NativeUnion.ts
  test/generated/output/clone/test_clone_ToJsonUnion.ts
  test/generated/output/createAssertClone/test_createAssertClone_NativeUnion.ts
  test/generated/output/createAssertClone/test_createAssertClone_ToJsonUnion.ts
  test/generated/output/createAssertStringify/test_createAssertStringify_NativeUnion.ts
  test/generated/output/createAssertStringify/test_createAssertStringify_ToJsonDouble.ts
  test/generated/output/createAssertStringify/test_createAssertStringify_ToJsonTuple.ts
  test/generated/output/createAssertStringify/test_createAssertStringify_ToJsonUnion.ts
  test/generated/output/createClone/test_createClone_NativeUnion.ts
  test/generated/output/createClone/test_createClone_ToJsonUnion.ts
  test/generated/output/createIsClone/test_createIsClone_NativeUnion.ts
  test/generated/output/createIsClone/test_createIsClone_ToJsonUnion.ts
  test/generated/output/createIsStringify/test_createIsStringify_NativeUnion.ts
  test/generated/output/createIsStringify/test_createIsStringify_ToJsonDouble.ts
  test/generated/output/createIsStringify/test_createIsStringify_ToJsonTuple.ts
  test/generated/output/createIsStringify/test_createIsStringify_ToJsonUnion.ts
  test/generated/output/createStringify/test_createStringify_NativeUnion.ts
  test/generated/output/createStringify/test_createStringify_ToJsonDouble.ts
  test/generated/output/createStringify/test_createStringify_ToJsonTuple.ts
  test/generated/output/createStringify/test_createStringify_ToJsonUnion.ts
  test/generated/output/createValidateClone/test_createValidateClone_NativeUnion.ts
  test/generated/output/createValidateClone/test_createValidateClone_ToJsonUnion.ts
  test/generated/output/createValidateStringify/test_createValidateStringify_NativeUnion.ts
  test/generated/output/createValidateStringify/test_createValidateStringify_ToJsonDouble.ts
  test/generated/output/createValidateStringify/test_createValidateStringify_ToJsonTuple.ts
  test/generated/output/createValidateStringify/test_createValidateStringify_ToJsonUnion.ts
  test/generated/output/isClone/test_isClone_NativeUnion.ts
  test/generated/output/isClone/test_isClone_ToJsonUnion.ts
  test/generated/output/isStringify/test_isStringify_ToJsonDouble.ts
  test/generated/output/isStringify/test_isStringify_ToJsonTuple.ts
  test/generated/output/isStringify/test_isStringify_ToJsonUnion.ts
  test/generated/output/stringify/test_stringify_ToJsonDouble.ts
  test/generated/output/stringify/test_stringify_ToJsonTuple.ts
  test/generated/output/stringify/test_stringify_ToJsonUnion.ts
  test/generated/output/validateClone/test_validateClone_NativeUnion.ts
  test/generated/output/validateClone/test_validateClone_ToJsonUnion.ts
  test/generated/output/validateStringify/test_validateStringify_ToJsonDouble.ts
  test/generated/output/validateStringify/test_validateStringify_ToJsonTuple.ts
  test/generated/output/validateStringify/test_validateStringify_ToJsonUnion.ts
  test/issues/resolved.ts
  test/schemas/json/ajv/NativeUnion.json
  test/schemas/json/ajv/ToJsonUnion.json
  test/schemas/json/swagger/NativeUnion.json
  test/schemas/json/swagger/ToJsonUnion.json
Labels: bug, enhancement

#662 Fix samchon/nestia#394 - intersection type in JSON schema
  .eslintrc.cjs
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/iterate_metadata.ts
  src/factories/internal/metadata/iterate_metadata_alias.ts
  src/factories/internal/metadata/iterate_metadata_intersection.ts
  src/programmers/helpers/PruneJoiner.ts
  test/issues/nestia-394.ts
Labels: bug, enhancement

#663 Improve the performance of validate
  src/programmers/ValidateProgrammer.ts
Labels: enhancement, good first issue

#672 Enhance `IJsonSchema.ITuple` type.
  package.json
  packages/typescript-json/package.json
  src/factories/CommentFactory.ts
  src/factories/IdentifierFactory.ts
  src/factories/MetadataFactory.ts
  src/programmers/ApplicationProgrammer.ts
  src/programmers/AssertCloneProgrammer.ts
  src/programmers/AssertParseProgrammer.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/AssertPruneProgrammer.ts
  src/programmers/AssertStringifyProgrammer.ts
  src/programmers/CloneProgrammer.ts
  src/programmers/IsCloneProgrammer.ts
  src/programmers/IsParseProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/IsPruneProgrammer.ts
  src/programmers/IsStringifyProgrammer.ts
  src/programmers/LiteralsProgrammer.ts
  src/programmers/PruneProgrammer.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/ValidateCloneProgrammer.ts
  src/programmers/ValidateParseProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/ValidatePruneProgrammer.ts
  src/programmers/ValidateStringifyProgrammer.ts
  src/programmers/internal/application_tuple.ts
  src/schemas/IJsonSchema.ts
  test/issues/ajv.js
  test/issues/ajv.ts
Labels: enhancement

#677 Static playground website
  .vscode/settings.json
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/iterate_metadata_array.ts
  test/issues/array.ts
  test/issues/generate/532.ts
  test/issues/generate/573.ts
  test/issues/generate/575.ts
  test/issues/generate/617.ts
  test/issues/generate/input/playground.ts
  test/issues/generate/nestia-282.ts
  test/issues/generate/playground.ts
  test/issues/playground.ts
  website/.gitignore
  website/.prettierignore
  website/compilers/Compiler.ts
  website/components/OutputViewer.tsx
  website/components/SourceEditor.tsx
  website/css/playground/layout.module.css
  website/css/playground/resizer.module.css
  website/deploy.js
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_meta.json
  website/pages/playground/index.tsx
  website/prettier.config.js
  website/public/sitemap-0.xml
  website/raw.js
  website/tsconfig.json
Labels: documentation, enhancement

#682 Server benchmark on i5-1135g7
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/README.md
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert-error.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/assert.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/is.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/optimizer.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/server-assert.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/server-performance.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/server-stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/stringify.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate-error.svg
  benchmark/results/11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz/images/validate.svg
Labels: documentation

#684 Abandon `react-split-pane`
  website/css/playground/resizer.module.css
  website/package-lock.json
  website/package.json
  website/pages/docs/validators/assert.mdx
  website/pages/docs/validators/is.mdx
  website/pages/docs/validators/validate.mdx
  website/pages/playground/index.tsx
  website/public/images/github.svg
  website/public/sitemap-0.xml
  website/src/components/OutputViewer.tsx
  website/src/components/SourceEditor.tsx
  website/src/components/Splitter.tsx
  website/src/pages/Playground.tsx
  website/src/styles/layout.module.css
  website/src/utils/Compiler.ts
  website/src/utils/Expander.ts
Labels: documentation

#696 Add generation mode on playground website
  website/public/images/playground/javascript.png
  website/public/images/playground/typescript.png
  website/public/sitemap-0.xml
  website/src/components/LanguageButton.tsx
  website/src/components/OutputViewer.tsx
  website/src/components/SourceEditor.tsx
  website/src/pages/Playground.tsx
  website/src/utils/Compiler.ts
  website/theme.config.tsx
Labels: documentation
