Repository samchon/typia, pull requests merged in 2023-02, with the labels that each got.

#479 Close #478 - optimize strict validator when no dynamic property exists
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/programmers/internal/check_dynamic_properties.ts
  test/issues/478.ts
Labels: enhancement

#483 Close #482 - optimize `equals()` for simple object
  package.json
  packages/typescript-json/package.json
  src/programmers/CheckerProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/helpers/StringifyJoinder.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/check_object.ts
  test/issues/480.ts
Labels: enhancement

#484 Complement #480 - only for `equals()`
  package.json
  packages/typescript-json/package.json
  src/programmers/AssertProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/transformers/ITransformOptions.ts
  test/issues/480.ts
Labels: enhancement

#490 Close #489 - support atomic class types
  package.json
  packages/typescript-json/package.json
  packages/typescript-json/tsconfig.json
  src/factories/internal/metadata/iterate_metadata_native.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/helpers/AtomicPredicator.ts
  src/programmers/internal/application_schema.ts
  src/programmers/internal/check_native.ts
  test/features/application/ajv/test_application_ajv_AtomicClass.ts
  test/features/application/swagger/test_application_swagger_AtomicClass.ts
  test/features/assert/test_assert_AtomicClass.ts
  test/features/assertEquals/test_assertEquals_AtomicClass.ts
  test/features/assertParse/test_assertParse_AtomicClass.ts
  test/features/assertStringify/test_assertStringify_AtomicClass.ts
  test/features/createAssert/test_createAssert_AtomicClass.ts
  test/features/createAssertEquals/test_createAssertEquals_AtomicClass.ts
  test/features/createAssertParse/test_createAssertParse_AtomicClass.ts
  test/features/createAssertStringify/test_createAssertStringify_AtomicClass.ts
  test/features/createEquals/test_createEquals_AtomicClass.ts
  test/features/createIs/test_createIs_AtomicClass.ts
  test/features/createIsParse/test_createIsParse_AtomicClass.ts
  test/features/createIsStringify/test_createIsStringify_AtomicClass.ts
  test/features/createStringify/test_createStringify_AtomicClass.ts
  test/features/createValidate/test_createValidate_AtomicClass.ts
  test/features/createValidateEquals/test_createValidateEquals_AtomicClass.ts
  test/features/createValidateParse/test_createValidateParse_AtomicClass.ts
  test/features/createValidateStringify/test_createValidateStringify_AtomicClass.ts
  test/features/equals/test_equals_AtomicClass.ts
  test/features/is/test_is_AtomicClass.ts
  test/features/isParse/test_isParse_AtomicClass.ts
  test/features/isStringify/test_isStringify_AtomicClass.ts
  test/features/stringify/test_stringify_AtomicClass.ts
  test/features/validate/test_validate_AtomicClass.ts
  test/features/validateEquals/test_validateEquals_AtomicClass.ts
  test/features/validateParse/test_validateParse_AtomicClass.ts
  test/features/validateStringify/test_validateStringify_AtomicClass.ts
  test/issues/488.ts
  test/schemas/json/ajv/AtomicClass.json
  test/schemas/json/swagger/AtomicClass.json
  test/structures/AtomicClass.ts
  tsconfig.json
Labels: enhancement

#492 Close #491 - documentate `FeatureProgrammer`
  src/programmers/FeatureProgrammer.ts
  src/programmers/StringifyProgrammer.ts
Labels: documentation, enhancement

#498 benchmark xeon w3235
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/README.md
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/assertEquals_po_iterate_pc.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/assertEquals_po_throw_pc.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/assert_po_iterate_pc.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/assert_po_throw_pc.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/equals.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/is.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/optimizer.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/stringify.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/stringify_po_server_pc.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/validate.svg
  benchmark/results/Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz/images/validateEquals.svg
Labels: documentation

#506 Close #505 - enhance setup wizard
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/executable/internal/ArgumentParser.ts
  src/executable/internal/CommandExecutor.ts
  src/executable/internal/CommandParser.ts
  src/executable/internal/PackageManager.ts
  src/executable/internal/PluginConfigurator.ts
  src/executable/internal/TypiaSetupWizard.ts
  src/executable/typia.ts
Labels: enhancement

#507 Update README
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/executable/internal/ArgumentParser.ts
  src/executable/internal/PluginConfigurator.ts
  src/executable/typia.ts
Labels: documentation, enhancement

#512 Close #511 - `random()` became customizable
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/IRandomGenerator.ts
  src/executable/TypiaSetupWizard.ts
  src/executable/setup/ArgumentParser.ts
  src/executable/setup/CommandExecutor.ts
  src/executable/setup/PackageManager.ts
  src/executable/setup/PluginConfigurator.ts
  src/executable/typia.ts
  src/module.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/helpers/RandomJoiner.ts
  src/programmers/helpers/RandomRanger.ts
  test/features/internal/_test_assertParse.ts
  test/features/internal/_test_isParse.ts
  test/features/internal/_test_validateParse.ts
  test/issue.js
  test/manual.js
  test/tsconfig.issue.json
Labels: enhancement

#517 Fix #516 (setup wizard) for yarn monorepo
  package.json
  packages/typescript-json/package.json
  src/executable/setup/ArgumentParser.ts
  src/executable/setup/FileRetriever.ts
  src/executable/setup/PackageManager.ts
  src/executable/setup/PluginConfigurator.ts
Labels: bug

#518 Fix #515 - remove unused locals, but not perfect yet
  package.json
  packages/typescript-json/package.json
  src/programmers/AssertProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/CloneProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/PruneProgrammer.ts
  src/programmers/StringifyProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/helpers/FunctionImporeter.ts
  src/programmers/internal/feature_object_entries.ts
  test/copiers/assertType.js
  test/copiers/escape.js
  test/issues/515.ts
Labels: bug, enhancement

#523 Fix: exact package.json exploration logic
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/executable/setup/FileRetriever.ts
Labels: bug, enhancement

#526 Close #525 - README for generation mode
  README.md
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
Labels: documentation, enhancement
