Repository samchon/typia, pull requests merged in 2023-01, with the labels that each got.

#457 Fix #456 - complicate instance union type case
  package.json
  packages/typescript-json/package.json
  src/metadata/Metadata.ts
  src/programmers/AssertProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/helpers/UnionExplorer.ts
  src/programmers/internal/check_array.ts
  src/programmers/internal/check_array_length.ts
  src/programmers/internal/check_union_array_like.ts
  src/programmers/internal/check_union_tuple.ts
  test/issues/456.ts
Labels: bug

#463 Add 12th Gen Intel(R) Core(TM) i7-12700H results
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/README.md
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/assertEquals_po_iterate_pc.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/assertEquals_po_throw_pc.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/assert_po_iterate_pc.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/assert_po_throw_pc.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/equals.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/is.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/optimizer.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/stringify.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/stringify_po_server_pc.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/validate.svg
  benchmark/results/12th Gen Intel(R) Core(TM) i7-12700H/images/validateEquals.svg
Labels: enhancement

#466 Complement #464 - special JSON schema expression for rest tuple type
  package.json
  packages/typescript-json/package.json
  src/programmers/internal/application_schema.ts
  test/schemas/json/ajv/TupleRestArray.json
  test/schemas/json/ajv/TupleRestAtomic.json
  test/schemas/json/ajv/TupleRestObject.json
Labels: enhancement

#468 Complement #364 - exact array and map types
  package.json
  packages/typescript-json/package.json
  src/factories/internal/protocols/ProtocolMetadataUtil.ts
  src/factories/internal/protocols/iterate_protocol_map.ts
  src/factories/internal/protocols/iterate_protocol_metadata.ts
  src/factories/internal/protocols/iterate_protocol_repeated.ts
  src/messages/IProtocolMap.ts
  src/messages/IProtocolProperty.ts
  src/programmers/MessageProgrammer.ts
  test/issues/364.ts
  test/schemas/protobuf/ArrayAtomicAlias.proto
  test/schemas/protobuf/ArrayAtomicSimple.proto
  test/schemas/protobuf/ArrayMatrix.proto
  test/schemas/protobuf/DynamicArray.proto
  test/schemas/protobuf/DynamicSimple.proto
  test/schemas/protobuf/DynamicTemplate.proto
  test/schemas/protobuf/DynamicTree.proto
  test/schemas/protobuf/ObjectDynamic.proto
  test/schemas/protobuf/ObjectUnionDouble.proto
  test/schemas/protobuf/SetAlias.proto
  test/schemas/protobuf/SetSimple.proto
  test/schemas/protobuf/SetUnion.proto
  test/schemas/protobuf/TagArray.proto
  test/schemas/protobuf/TagTuple.proto
  test/schemas/protobuf/UltimateUnion.proto
Labels: bug, enhancement

#470 Complement #364 - validate through `ts-proto`
  .gitignore
  build/internal/TestMessageGenerator.ts
  package.json
  packages/typescript-json/package.json
  src/factories/ProtocolFactory.ts
  src/factories/internal/protocols/ProtocolMetadataUtil.ts
  src/factories/internal/protocols/emplace_protocol_object.ts
  src/factories/internal/protocols/iterate_protocol_map.ts
  src/factories/internal/protocols/iterate_protocol_metadata.ts
  src/factories/internal/protocols/iterate_protocol_never.ts
  src/factories/internal/protocols/iterate_protocol_object.ts
  src/factories/internal/protocols/iterate_protocol_tuple.ts
  src/metadata/Metadata.ts
  src/programmers/MessageProgrammer.ts
  test/issues/364.ts
  test/schemas/protobuf/ArrayRecursiveUnionExplicit.proto
  test/schemas/protobuf/ArrayRecursiveUnionImplicit.proto
  test/schemas/protobuf/ArraySimple.proto
  test/schemas/protobuf/ArrayUnion.proto
  test/schemas/protobuf/AtomicUnion.proto
  test/schemas/protobuf/ConstantAtomicUnion.proto
  test/schemas/protobuf/ConstantConstEnumeration.proto
  test/schemas/protobuf/ConstantEnumeration.proto
  test/schemas/protobuf/DynamicArray.proto
  test/schemas/protobuf/DynamicTemplate.proto
  test/schemas/protobuf/ObjectAlias.proto
  test/schemas/protobuf/ObjectDynamic.proto
  test/schemas/protobuf/ObjectGenericUnion.proto
  test/schemas/protobuf/ObjectNullable.proto
  test/schemas/protobuf/ObjectUnionComposite.proto
  test/schemas/protobuf/ObjectUnionDouble.proto
  test/schemas/protobuf/ObjectUnionExplicit.proto
  test/schemas/protobuf/ObjectUnionImplicit.proto
  test/schemas/protobuf/ObjectUnionNonPredictable.proto
  test/schemas/protobuf/SetUnion.proto
  test/schemas/protobuf/TagArray.proto
  test/schemas/protobuf/TagAtomicUnion.proto
  test/schemas/protobuf/TagDefault.proto
  test/schemas/protobuf/TagObjectUnion.proto
  test/schemas/protobuf/TemplateUnion.proto
  test/schemas/protobuf/TupleHierarchical.proto
  test/schemas/protobuf/TupleRestArray.proto
  test/schemas/protobuf/TupleRestAtomic.proto
  test/schemas/protobuf/TupleRestObject.proto
  test/schemas/protobuf/UltimateUnion.proto
  tsconfig.test.json
Labels: bug, enhancement
