Repository samchon/typia, pull requests merged in 2023-11, with the labels that each got.

#863 Break change from `ts.factory.createNumericLiteral()`.
  package.json
  packages/typescript-json/package.json
  src/factories/ExpressionFactory.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/helpers/RandomJoiner.ts
  src/programmers/helpers/RandomRanger.ts
  src/programmers/http/HttpHeadersProgrammer.ts
  src/programmers/internal/check_dynamic_properties.ts
  src/programmers/internal/check_union_array_like.ts
  src/programmers/json/JsonStringifyProgrammer.ts
  src/programmers/misc/MiscCloneProgrammer.ts
  src/programmers/misc/MiscLiteralsProgrammer.ts
  src/programmers/misc/MiscPruneProgrammer.ts
  src/programmers/notations/NotationGeneralProgrammer.ts
  src/programmers/protobuf/ProtobufDecodeProgrammer.ts
  src/programmers/protobuf/ProtobufEncodeProgrammer.ts
  website/package-lock.json
  website/package.json
  website/public/sitemap-0.xml
  website/src/utils/Compiler.ts
Labels: enhancement

#877 Fixed the typia homepage address.
  src/http.ts
  src/misc.ts
Labels: bug, documentation

#879 Warning message when `jsDocParsingMode` is not hacked.
  package.json
  packages/typescript-json/package.json
  src/transformers/FileTransformer.ts
Labels: documentation, enhancement

#883 New cli command `npx typia patch` for hacking `defaultJSDocParsingMode` value
  deploy/internal/ReplicaPublisher.ts
  package.json
  packages/benchmark/package.json
  packages/errors/package.json
  packages/test/package.json
  packages/typescript-json/package.json
  src/executable/TypiaPatchWizard.ts
  src/executable/TypiaSetupWizard.ts
  src/executable/typia.ts
  src/transformers/FileTransformer.ts
  website/package-lock.json
  website/package.json
  website/pages/docs/setup.mdx
Labels: enhancement

#882 Complement #865 - documentation
  website/pages/docs/setup.mdx
Labels: documentation, enhancement, good first issue

#886 Fix #884 - wrong union predication about constant type
  package.json
  packages/benchmark/package.json
  packages/errors/package.json
  packages/test/package.json
  packages/typescript-json/package.json
  src/schemas/metadata/Metadata.ts
Labels: bug

#891 Fix length error of `typia.random<T>()` function.
  package.json
  packages/benchmark/package.json
  packages/errors/package.json
  packages/test/package.json
  packages/typescript-json/package.json
  src/programmers/helpers/RandomRanger.ts
  src/transformers/CallExpressionTransformer.ts
  website/package-lock.json
  website/package.json
  website/public/sitemap-0.xml
Labels: bug, enhancement

#895 Fix #893 - erase `@internal` tag from `IMetadataDictionary`.
  package.json
  packages/benchmark/package.json
  packages/errors/package.json
  packages/test/package.json
  packages/typescript-json/package.json
  src/module.ts
  src/schemas/metadata/IMetadataDictionary.ts
Labels: bug
