Repository samchon/typia, pull requests merged in 2024-12, with the labels that each got.

#1401 1st completion of documentation
  package.json
  packages/typescript-json/package.json
  src/factories/ExpressionFactory.ts
  src/programmers/ImportProgrammer.ts
  src/programmers/json/JsonApplicationProgrammer.ts
  src/transformers/features/json/JsonSchemasTransformer.ts
  src/transformers/features/llm/LlmApplicationTransformer.ts
  src/transformers/features/llm/LlmParametersTransformer.ts
  src/transformers/features/llm/LlmSchemaTransformer.ts
  test/generate/output/generate_json.ts
  test/generate/output/generate_llm.ts
  test/src/debug/example.js
  test/src/debug/intersection.ts
  test/src/debug/llm.application.separate.ts
  test/src/debug/llm.application.ts
  website/package.json
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/parameters.mdx
  website/pages/docs/llm/schema.mdx
Labels: bug, documentation, enhancement

#1349 replace URLSearchParams to IReadableURLSearchParams
  src/IReadableURLSearchParams.ts
  src/http.ts
Labels: documentation, enhancement, good first issue

#1402 Emend #1349: publish `IReadableURLSearchParams` in v7 major update.
  src/IReadableURLSearchParams.ts
  src/http.ts
  src/internal/_httpQueryParseURLSearchParams.ts
  src/module.ts
  src/programmers/http/HttpQueryProgrammer.ts
  test/generate/input/generate_http.ts
  test/generate/output/generate_http.ts
Labels: enhancement

#1405 Website compiled JS text renewal
  website/pages/docs/__templates/import.txt
  website/pages/docs/__templates/tab-aot.txt
  website/pages/docs/__templates/tab-module.txt
  website/pages/docs/json/parse.mdx
  website/pages/docs/json/schema.mdx
  website/pages/docs/json/stringify.mdx
  website/pages/docs/misc.mdx
  website/pages/docs/protobuf/decode.mdx
  website/pages/docs/protobuf/encode.mdx
  website/pages/docs/protobuf/message.mdx
  website/pages/docs/pure.mdx
  website/pages/docs/random.mdx
  website/pages/docs/setup.mdx
  website/pages/docs/validators/assert.mdx
  website/pages/docs/validators/functional.mdx
  website/pages/docs/validators/is.mdx
  website/pages/docs/validators/tags.mdx
  website/pages/docs/validators/validate.mdx
Labels: documentation

#1407 Description of `tags.Sequence<N>` type in the `protobuf` chapter.
  website/pages/docs/protobuf/decode.mdx
  website/pages/docs/protobuf/encode.mdx
  website/pages/docs/protobuf/message.mdx
Labels: documentation

#1408 Fix wrong file typo
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/parameters.mdx
  website/pages/docs/llm/schema.mdx
Labels: documentation

#1420 Report `TransformError` in website playground.
  website/src/compilers/TypeScriptCompiler.ts
  website/src/components/playground/OutputViewer.tsx
  website/src/pages/Playground.tsx
Labels: documentation

#1421 Add `IValidation.IError.data` property.
  .github/workflows/build.yml
  package.json
  src/IValidation.ts
  src/programmers/ValidateProgrammer.ts
  test/generate/output/generate_http.ts
  test/generate/output/generate_index.ts
  test/generate/output/generate_json.ts
  test/generate/output/generate_misc.ts
  test/generate/output/generate_notations.ts
  test/generate/output/generate_plain.ts
  test/generate/output/generate_protobuf.ts
  test/src/debug/validate.ts
  test/src/internal/_test_functional_validateFunction.ts
  test/src/internal/_test_functional_validateFunctionAsync.ts
  test/src/internal/_test_functional_validateParameters.ts
  test/src/internal/_test_functional_validateParametersAsync.ts
  test/src/internal/_test_functional_validateReturn.ts
  test/src/internal/_test_http_validateFormData.ts
  test/src/internal/_test_http_validateHeaders.ts
  test/src/internal/_test_http_validateQuery.ts
  test/src/internal/_test_json_validateParse.ts
  test/src/internal/_test_json_validateStringify.ts
  test/src/internal/_test_misc_validateClone.ts
  test/src/internal/_test_misc_validatePrune.ts
  test/src/internal/_test_notation_validateGeneral.ts
  test/src/internal/_test_protobuf_validateDecode.ts
  test/src/internal/_test_protobuf_validateEncode.ts
  test/src/internal/_test_validate.ts
  test/src/internal/_test_validateEquals.ts
  website/pages/docs/json/parse.mdx
  website/pages/docs/json/stringify.mdx
  website/pages/docs/misc.mdx
  website/pages/docs/protobuf/decode.mdx
  website/pages/docs/protobuf/encode.mdx
  website/pages/docs/validators/validate.mdx
Labels: enhancement

#1422 Adapt nextra v3 update
  website/next-env.d.ts
  website/next.config.mjs
  website/package.json
  website/pages/_meta.js
  website/pages/_meta.json
  website/pages/docs/_meta.js
  website/pages/docs/_meta.json
  website/pages/docs/json/_meta.js
  website/pages/docs/json/_meta.json
  website/pages/docs/json/parse.mdx
  website/pages/docs/json/schema.mdx
  website/pages/docs/json/stringify.mdx
  website/pages/docs/llm/_meta.js
  website/pages/docs/llm/_meta.json
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/parameters.mdx
  website/pages/docs/llm/schema.mdx
  website/pages/docs/misc.mdx
  website/pages/docs/protobuf/_meta.js
  website/pages/docs/protobuf/_meta.json
  website/pages/docs/protobuf/decode.mdx
  website/pages/docs/protobuf/encode.mdx
  website/pages/docs/protobuf/message.mdx
  website/pages/docs/pure.mdx
  website/pages/docs/random.mdx
  website/pages/docs/setup.mdx
  website/pages/docs/utilization/_meta.js
  website/pages/docs/utilization/_meta.json
  website/pages/docs/utilization/prisma.mdx
  website/pages/docs/validators/_meta.js
  website/pages/docs/validators/_meta.json
  website/pages/docs/validators/assert.mdx
  website/pages/docs/validators/functional.mdx
  website/pages/docs/validators/is.mdx
  website/pages/docs/validators/tags.mdx
  website/pages/docs/validators/validate.mdx
  website/pages/playground/_meta.js
  website/pages/playground/_meta.json
  website/theme.config.tsx
Labels: documentation, enhancement, dependencies

#1423 Refactor README and index.html
  README.md
  website/pages/_meta.js
  website/pages/docs/index.mdx
  website/pages/docs/validators/tags.mdx
  website/pages/index.mdx
  website/src/components/home/HomeLayout.tsx
Labels: documentation

#1424 Fixing #1227: documentation of `UniqueItems`
  website/pages/docs/validators/tags.mdx
Labels: documentation

#1427 Block LLM function schema composition by `@human` tag.
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/programmers/json/JsonApplicationProgrammer.ts
  src/programmers/llm/LlmApplicationProgrammer.ts
  test/debug.ts
  test/generate/output/generate_http.ts
  test/generate/output/generate_index.ts
  test/generate/output/generate_json.ts
  test/generate/output/generate_misc.ts
  test/generate/output/generate_notations.ts
  test/generate/output/generate_plain.ts
  test/generate/output/generate_protobuf.ts
  test/issue.ts
  test/package.json
  test/src/debug/llm.application.ts
  test/src/features/issues/test_issue_openapi_106_human.ts
  website/pages/docs/llm/application.mdx
Labels: documentation, enhancement

#1438 Fix LLM schema recursive type detector.
  package.json
  packages/typescript-json/package.json
  src/factories/JsonMetadataFactory.ts
  src/programmers/llm/LlmSchemaProgrammer.ts
  test-error/src/llm/llm.gemini.recursive.ts
  test-error/src/llm/llm.v30.recursive.ts
Labels: bug, enhancement

#1440 Adapt `@samchon/openapi@2.3.0`.
  package.json
  packages/typescript-json/package.json
  src/programmers/llm/LlmApplicationProgrammer.ts
  test-error/src/llm/llm.application.name.ts
Labels: documentation, enhancement

#1442 Fix `ILlmFunction.parameters.description` problem.
  package.json
  src/programmers/llm/LlmApplicationProgrammer.ts
  test/src/debug/llm.application.ts
  test/src/features/issues/test_pr_1442_llm_function_parameters_description.ts
Labels: bug, enhancement

#1443 Detailed documentation about `typia.llm.application()` function
  website/pages/docs/llm/_meta.js
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/strategy.mdx
Labels: documentation

#1450 Detailed description of `typia.llm.parameters()` function.
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/parameters.mdx
Labels: documentation, enhancement
