Repository samchon/typia, pull requests merged in 2024-06, with the labels that each got.

#1066 Close #1062: add new type tag `UniqueItems`.
  benchmark/package.json
  debug/features/unique.ts
  debug/index.js
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataCommentTagFactory.ts
  src/tags/UniqueItems.ts
  src/tags/index.ts
  test/package.json
  test/schemas/json/v3_0/CommentTagArray.json
  test/schemas/json/v3_0/TypeTagArray.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/CommentTagArray.json
  test/schemas/json/v3_1/TypeTagArray.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/protobuf/CommentTagArray.proto
  test/schemas/protobuf/TypeTagArray.proto
  test/schemas/reflect/metadata/CommentTagArray.json
  test/schemas/reflect/metadata/ObjectDate.json
  test/schemas/reflect/metadata/TypeTagArray.json
  test/schemas/reflect/metadata/UltimateUnion.json
  test/src/structures/CommentTagArray.ts
  test/src/structures/TypeTagArray.ts
  website/package.json
Labels: enhancement

#1070 Adapt nonara/ts-patch#154: TS 5.5 issue
  .github/dependabot.yml
  benchmark/package.json
  deploy/index.ts
  package.json
  test/package.json
  website/pages/docs/setup.mdx
Labels: enhancement

#1072 Complement #1062: `UniqueItems<false>` case.
  benchmark/package.json
  debug/features/unique.ts
  debug/package.json
  debug/tsconfig.json
  deploy/index.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataCommentTagFactory.ts
  src/tags/UniqueItems.ts
  test-esm/package.json
  test/package.json
  test/schemas/reflect/metadata/CommentTagArray.json
  test/schemas/reflect/metadata/TypeTagArray.json
  test/src/features/issues/test_issue_1062_uniqueItems.ts
  website/package.json
Labels: bug, enhancement

#1074 feat(setup.md): added how to integrate with `typia` w/ `unplugin-typia`
  website/package-lock.json
  website/pages/docs/setup.mdx
Labels: documentation, enhancement, good first issue

#1086 `unplugin-typia` to be main feature of setup guide docs
  website/pages/docs/setup.mdx
Labels: documentation, enhancement

#1092 feat: Replace dax-sh with child_process for check if bun is available
  deploy/index.ts
  package.json
Labels: enhancement, good first issue

#1109 Fix #1108: recursive array with type tag problem
  benchmark/package.json
  debug/features/recursive.ts
  debug/package.json
  deploy/index.ts
  deploy/internal/DeployRunner.ts
  deploy/internal/ReplicaPublisher.ts
  deploy/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataCollection.ts
  src/factories/internal/metadata/iterate_metadata_intersection.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1108_recursive_array_with_items_tag.ts
  website/package-lock.json
  website/package.json
Labels: bug

#1111 Close #1110: support `@description` tag in JSON schema.
  benchmark/package.json
  debug/features/description.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/internal/application_description.ts
  src/programmers/internal/application_v30_alias.ts
  src/programmers/internal/application_v30_object.ts
  src/programmers/internal/application_v31_alias.ts
  src/programmers/internal/application_v31_object.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1100_json_description.ts
  website/package.json
Labels: enhancement

#1115 Block TypeScript v5.5 for a while.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  test-esm/package.json
  test/package.json
Labels: bug, enhancement

#1122 Fix #1121: recursive array problem in JSON schema.
  benchmark/package.json
  debug/features/array.ts
  debug/features/prisma.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/emplace_metadata_array_type.ts
  src/factories/internal/metadata/iterate_metadata_array.ts
  src/programmers/internal/application_array.ts
  src/programmers/internal/application_v30_schema.ts
  src/programmers/internal/application_v31_schema.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/ArrayRepeatedNullable.json
  test/schemas/json/v3_0/ArrayRepeatedRequired.json
  test/schemas/json/v3_0/ArrayRepeatedUnion.json
  test/schemas/json/v3_0/ArrayRepeatedUnionWithTuple.json
  test/schemas/json/v3_1/ArrayRepeatedNullable.json
  test/schemas/json/v3_1/ArrayRepeatedRequired.json
  test/schemas/json/v3_1/ArrayRepeatedUnion.json
  test/schemas/json/v3_1/ArrayRepeatedUnionWithTuple.json
  test/schemas/reflect/metadata/DynamicJsonValue.json
Labels: bug

#1126 Prepare #1055: `TypeGuardError<T>` for assigning issue.
  deploy/package.json
  src/TypeGuardError.ts
Labels: enhancement

#1120 Close #1119: new function `typia.reflect.name<T>()`.
  benchmark/package.json
  debug/features/name.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/reflect.ts
  src/transformers/CallExpressionTransformer.ts
  src/transformers/features/reflect/ReflectMetadataTransformer.ts
  src/transformers/features/reflect/ReflectNameTransformer.ts
  test-esm/package.json
  test/package.json
Labels: enhancement

#1128 Revert "refactor: improve tree-shaking in ESM target"
  package.json
  rollup.config.js
  src/functional.ts
  src/functional/$ProtobufReader.ts
  src/functional/$ProtobufSizer.ts
  src/functional/$ProtobufWriter.ts
  src/http.ts
  src/json.ts
  src/misc.ts
  src/module.ts
  src/notations.ts
  src/protobuf.ts
  src/reflect.ts
Labels: bug

#1129 Upgrade `ts-patch@3.2.1` for `typescript@5.2.2`.
  benchmark/package.json
  deploy/index.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  test-esm/package.json
  test/package.json
  website/package-lock.json
  website/package.json
Labels: bug, enhancement

#1131 Bump `@samchon/openapi`
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  test-esm/package.json
  test/package.json
  website/package.json
Labels: enhancement

#1132 Bump `typedoc` of website for latest `typescript`.
  website/package-lock.json
  website/package.json
Labels: bug
