Repository samchon/typia, pull requests merged in 2024-07, with the labels that each got.

#1139 Fix #1138: `typia.random<T>()` for `UniqueItems` tag.
  benchmark/package.json
  debug/features/random.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/IRandomGenerator.ts
  src/executable/TypiaSetupWizard.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/helpers/RandomJoiner.ts
  src/utils/RandomGenerator/RandomGenerator.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1138_random_uniqueItems.ts
  website/package-lock.json
  website/package.json
Labels: bug, enhancement

#1141 Fix #1054: utilize `Set<T>` for a lot of constant values type case.
  benchmark/package.json
  debug/features/set.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/helpers/FunctionImporter.ts
  src/programmers/helpers/disable_function_importer_declare.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1054_check_constants_by_set.ts
Labels: enhancement

#1133 feat(rollup.config): improve tree-shaking using `preserveModules: true`
  package.json
  rollup.config.js
Labels: enhancement, good first issue, invalid

#1143 Upgrade `@samchon/openapi` dependency.
  benchmark/package.json
  deploy/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/reflect/metadata/UltimateUnion.json
  website/package-lock.json
  website/package.json
Labels: enhancement

#1146 feat(package.json): add sideEffects property
  package.json
Labels: enhancement

#1148 Revise sponsors chapter
  README.md
  website/pages/docs/index.mdx
  website/pages/index.mdx
Labels: documentation

#1150 Close #1149: `IJsonSchema.IOneOf.discriminator`.
  benchmark/package.json
  debug/features/discriminator.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/programmers/internal/application_union_discriminator.ts
  src/programmers/internal/application_v30_schema.ts
  src/programmers/internal/application_v31_schema.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/ObjectNullable.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/ObjectNullable.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/reflect/metadata/UltimateUnion.json
  test/src/features/issues/test_issue_1149_json_schema_oneof_discriminator.ts
  website/package.json
Labels: enhancement

#1151 `HttpQueryProgrammer.allowOptional` configuration for `@nestia/sdk`.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/http/HttpAssertQueryProgrammer.ts
  src/programmers/http/HttpIsQueryProgrammer.ts
  src/programmers/http/HttpQueryProgrammer.ts
  src/programmers/http/HttpValidateQueryProgrammer.ts
  test-esm/package.json
  test/package.json
Labels: enhancement

#1153 Fix #1152: stop using `BigInt` global variables for super old browsers.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/functional/$ProtobufReader.ts
  src/functional/$ProtobufSizer.ts
  src/functional/$ProtobufWriter.ts
  test-esm/package.json
  test/package.json
  website/package.json
Labels: bug

#1159 Break change from `@samchon/openapi`.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  test-esm/package.json
  test/package.json
  website/package.json
Labels: enhancement

#1162 Fix #1161: change `$clone()` proper.
  benchmark/package.json
  debug/features/clone.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/functional/$any.ts
  src/functional/$clone.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1161_clone_was_wrong.ts
  website/package.json
Labels: bug

#1168 Fix `$clone()` function for `File` class case.
  src/functional/$clone.ts
Labels: bug

#1167 feat: add `Equal` type of Comparison of equivalence
  src/CamelCase.ts
  src/PascalCase.ts
  src/Primitive.ts
  src/Resolved.ts
  src/SnakeCase.ts
  src/typings/Equal.ts
Labels: enhancement, good first issue

#1170 Avoid bug of bun
  test/src/features/issues/test_issue_1161_clone_was_wrong.ts
  test/src/helpers/DynamicImportIterator.ts
Labels: bug, enhancement

#1171 Enhance internal `$clone()` function to consider older NodeJS versions.
  src/functional/$clone.ts
Labels: enhancement

#1169 Type resolver refactoring.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/CamelCase.ts
  src/PascalCase.ts
  src/Primitive.ts
  src/Resolved.ts
  src/SnakeCase.ts
  src/factories/internal/metadata/iterate_metadata_native.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/misc/MiscCloneProgrammer.ts
  src/typings/Equal.ts
  src/typings/IsTuple.ts
  src/typings/NativeClass.ts
  src/typings/ValueOf.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_pr_1169_native_class_regexp.ts
Labels: enhancement

#1174 Fix #1166: nonsensible intersection type case
  benchmark/package.json
  debug/features/intersection.ts
  debug/package.json
  errors/package.json
  errors/src/nonsensible/error_nonsensible_intersection.ts
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/iterate_metadata_intersection.ts
  test-esm/package.json
  test/package.json
  website/package.json
Labels: bug, enhancement

#1182 Close #1181: support enumeration level description comment in JSON schema.
  benchmark/package.json
  debug/features/enum.ts
  debug/features/internal/TestValidator.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/internal/metadata/iterate_metadata_constant.ts
  src/programmers/internal/application_description.ts
  src/programmers/internal/application_title.ts
  src/programmers/internal/application_v31_alias.ts
  src/programmers/internal/application_v31_constant.ts
  src/programmers/internal/application_v31_object.ts
  src/schemas/metadata/IMetadataConstantValue.ts
  src/schemas/metadata/MetadataConstantValue.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/src/features/issues/test_issue_1179_tuple_type_in_dynamic_object.ts
  test/src/features/issues/test_issue_1181_enum_description.ts
  website/package.json
Labels: documentation, enhancement

#1185 Enhance `MetadataObject.isLiteral()` function.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/IsProgrammer.ts
  src/programmers/internal/application_escaped.ts
  src/programmers/internal/application_union_discriminator.ts
  src/programmers/internal/application_v30_object.ts
  src/programmers/internal/application_v31_object.ts
  src/programmers/internal/application_v31_schema.ts
  src/programmers/json/JsonStringifyProgrammer.ts
  src/schemas/metadata/MetadataConstantValue.ts
  src/schemas/metadata/MetadataObject.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/ObjectLiteralType.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/ObjectLiteralType.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/reflect/metadata/ConstantConstEnumeration.json
  test/schemas/reflect/metadata/ConstantEnumeration.json
  test/schemas/reflect/metadata/UltimateUnion.json
  website/package.json
Labels: enhancement

#1189 Fix #1188: invalid JSON schema about tuple type.
  benchmark/package.json
  debug/features/enum.ts
  debug/features/internal/TestValidator.ts
  debug/features/join.ts
  debug/features/tuple.ts
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/internal/application_v31_tuple.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_1/ArrayAtomicAlias.json
  test/schemas/json/v3_1/ArrayAtomicSimple.json
  test/schemas/json/v3_1/ArrayRepeatedUnionWithTuple.json
  test/schemas/json/v3_1/AtomicAlias.json
  test/schemas/json/v3_1/AtomicClass.json
  test/schemas/json/v3_1/AtomicIntersection.json
  test/schemas/json/v3_1/AtomicSimple.json
  test/schemas/json/v3_1/ConstantAtomicSimple.json
  test/schemas/json/v3_1/ConstantAtomicWrapper.json
  test/schemas/json/v3_1/ConstantIntersection.json
  test/schemas/json/v3_1/ObjectGeneric.json
  test/schemas/json/v3_1/ObjectHierarchical.json
  test/schemas/json/v3_1/ObjectPropertyNullable.json
  test/schemas/json/v3_1/ObjectTuple.json
  test/schemas/json/v3_1/ToJsonArray.json
  test/schemas/json/v3_1/ToJsonAtomicSimple.json
  test/schemas/json/v3_1/ToJsonTuple.json
  test/schemas/json/v3_1/TupleHierarchical.json
  test/schemas/json/v3_1/TupleRestArray.json
  test/schemas/json/v3_1/TupleRestAtomic.json
  test/schemas/json/v3_1/TupleRestObject.json
  test/schemas/json/v3_1/TypeTagTuple.json
  test/src/features/issues/test_issue_1188_json_schema_tuple_type.ts
  website/package-lock.json
  website/package.json
Labels: bug, enhancement
