Repository samchon/typia, pull requests merged in 2024-05, with the labels that each got.

#1060 Feat: apply RFC3339 standard to typia.tags.Format<"date-time"|"date"|"time">
  src/tags/internal/FormatCheatSheet.ts
  src/utils/RandomGenerator/RandomGenerator.ts
  test/schemas/reflect/metadata/CommentTagFormat.json
  test/schemas/reflect/metadata/ObjectDate.json
  test/schemas/reflect/metadata/TypeTagFormat.json
  test/src/structures/ObjectDate.ts
  test/src/structures/TypeTagFormat.ts
Labels: enhancement

#1061 Fix dependabot tgz wrong path bug
  benchmark/package.json
  deploy/index.ts
  errors/package.json
  test/package.json
Labels: bug

#1045 Added additional clarification, fixed typos
  website/pages/docs/setup.mdx
Labels: documentation, enhancement, good first issue
