Repository samchon/typia, pull requests merged in 2024-08, with the labels that each got.

#1193 Documentation of v6.7 update.
  website/package-lock.json
  website/package.json
  website/pages/docs/__templates/tab-aot.txt
  website/pages/docs/_meta.json
  website/pages/docs/json/parse.mdx
  website/pages/docs/json/schema.mdx
  website/pages/docs/json/stringify.mdx
  website/pages/docs/misc.mdx
  website/pages/docs/protobuf/decode.mdx
  website/pages/docs/protobuf/encode.mdx
  website/pages/docs/protobuf/message.mdx
  website/pages/docs/pure.mdx
  website/pages/docs/random.mdx
  website/pages/docs/setup.mdx
  website/pages/docs/validators/assert.mdx
  website/pages/docs/validators/functional.mdx
  website/pages/docs/validators/is.mdx
  website/pages/docs/validators/tags.mdx
  website/pages/docs/validators/validate.mdx
  website/src/compilers/COMPILER_OPTIONS.ts
Labels: documentation, enhancement

#1197 Optimize `random()` and `clone()` functions.
  benchmark/package.json
  debug/package.json
  debug/src/clone.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/AssertProgrammer.ts
  src/programmers/CheckerProgrammer.ts
  src/programmers/FeatureProgrammer.ts
  src/programmers/IsProgrammer.ts
  src/programmers/RandomProgrammer.ts
  src/programmers/ValidateProgrammer.ts
  src/programmers/json/JsonIsParseProgrammer.ts
  src/programmers/json/JsonIsStringifyProgrammer.ts
  src/programmers/json/JsonStringifyProgrammer.ts
  src/programmers/json/JsonValidateParseProgrammer.ts
  src/programmers/json/JsonValidateStringifyProgrammer.ts
  src/programmers/misc/MiscCloneProgrammer.ts
  src/programmers/misc/MiscIsCloneProgrammer.ts
  src/programmers/misc/MiscIsPruneProgrammer.ts
  src/programmers/misc/MiscPruneProgrammer.ts
  src/programmers/misc/MiscValidateCloneProgrammer.ts
  src/programmers/misc/MiscValidatePruneProgrammer.ts
  src/programmers/notations/NotationGeneralProgrammer.ts
  src/programmers/notations/NotationValidateGeneralProgrammer.ts
  test-esm/package.json
  test/package.json
  website/package.json
Labels: enhancement

#1198 Fix generaton mode's non-initialized `let` variable problem.
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/StatementFactory.ts
  src/programmers/misc/MiscAssertPruneProgrammer.ts
  src/programmers/misc/MiscIsPruneProgrammer.ts
  src/programmers/misc/MiscValidatePruneProgrammer.ts
  src/programmers/notations/NotationGeneralProgrammer.ts
  src/programmers/notations/NotationValidateGeneralProgrammer.ts
  src/schemas/metadata/IMetadataConstantValue.ts
  src/schemas/metadata/IMetadataTemplate.ts
  test-esm/package.json
  test/.gitignore
  test/package.json
  test/tsconfig.actions.json
  test/tsconfig.generated.json
  website/package.json
Labels: bug, enhancement

#1200 Add `@samchon/openapi` types to playground editor.
  website/build/raw.js
  website/package-lock.json
  website/package.json
  website/src/compilers/TypeScriptCompiler.ts
Labels: documentation, enhancement

#1201 Support `console.info()` in playground
  website/src/components/playground/ConsoleViewer.tsx
  website/src/pages/Playground.tsx
Labels: documentation, enhancement

#1203 Playground console movie to handle async function.
  website/src/pages/Playground.tsx
Labels: documentation, enhancement

#1231 Adjust samchon/openapi#40 update to playground.
  website/package-lock.json
  website/package.json
Labels: bug, documentation

#1233 Fix #1232: enhance `tags.Pattern` type by type level JSON stringify.
  benchmark/package.json
  debug/package.json
  debug/src/bigint.ts
  debug/src/pattern.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/factories/MetadataCommentTagFactory.ts
  src/programmers/RandomProgrammer.ts
  src/tags/Pattern.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/CommentTagPattern.json
  test/schemas/json/v3_0/TypeTagPattern.json
  test/schemas/json/v3_1/CommentTagPattern.json
  test/schemas/json/v3_1/TypeTagPattern.json
  test/schemas/reflect/metadata/CommentTagPattern.json
  test/schemas/reflect/metadata/TypeTagPattern.json
  test/src/structures/CommentTagPattern.ts
  test/src/structures/TypeTagPattern.ts
  website/package.json
Labels: bug, enhancement

#1241 docs(setup): correct a small grammar mistake
  website/pages/docs/setup.mdx
Labels: documentation

#1242 Add more reserved keywords
  src/utils/Escaper.ts
Labels: enhancement

#1239 Close #760: `IJsonApplication<Version, Types>`
  benchmark/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/json.ts
  src/schemas/json/IJsonApplication.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/reflect/metadata/UltimateUnion.json
Labels: enhancement
