Repository samchon/typia, pull requests merged in 2024-09, with the labels that each got.

#1260 Description comments on LLM module.
  benchmark/package.json
  errors/package.json
  src/llm.ts
  test-esm/package.json
Labels: enhancement

#1261 LLM function calling parameter separation.
  benchmark/package.json
  debug/src/llm.ts
  debug/src/metadata.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/functional/Namespace/index.ts
  src/functional/Namespace/llm.ts
  src/llm.ts
  src/transformers/CallExpressionTransformer.ts
  src/transformers/features/llm/LlmApplicationTransformer.ts
  test-esm/package.json
  test/package.json
  test/src/features/llm.application/test_llm_application_separate.ts
Labels: enhancement

#1267 Documentation of LLM function callling appllication
  README.md
  benchmark/package.json
  debug/package.json
  debug/src/llm.schema.recursive.ts
  debug/src/llm.ts
  errors/package.json
  errors/src/llm/llm.application.bigint.ts
  package.json
  packages/typescript-json/README.md
  packages/typescript-json/package.json
  src/factories/MetadataFactory.ts
  src/factories/internal/metadata/emplace_metadata_object.ts
  src/factories/internal/metadata/iterate_metadata_comment_tags.ts
  src/factories/internal/metadata/iterate_metadata_function.ts
  src/llm.ts
  src/programmers/llm/LlmApplicationProgrammer.ts
  src/transformers/TransformerError.ts
  test-esm/package.json
  test/package.json
  website/package-lock.json
  website/package.json
  website/pages/docs/_meta.json
  website/pages/docs/json/schema.mdx
  website/pages/docs/llm/_meta.json
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/schema.mdx
  website/public/images/home/openai.svg
  website/src/components/home/HomeCodeBlock.tsx
  website/src/movies/home/HomeStrengthMovie.tsx
  website/src/movies/home/HomeStrengthSectionMovie.tsx
Labels: documentation, enhancement

#1269 CLI detects package manager automatically.
  .gitignore
  benchmark/package.json
  bin/typia.mjs
  errors/package.json
  package.json
  packages/typescript-json/package.json
  packages/typescript-json/tsconfig.json
  src/executable/TypiaSetupWizard.ts
  src/executable/setup/PackageManager.ts
  test-esm/package.json
  test/package.json
  tsconfig.cli.json
  tsconfig.json
Labels: enhancement

#1270 Publish v6.10 update with TS 6.2 adjusting
  benchmark/package.json
  debug/package.json
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/executable/TypiaSetupWizard.ts
  src/factories/internal/metadata/iterate_metadata_intersection.ts
  test-esm/package.json
  test/package.json
  test/src/helpers/TestValidator.ts
  website/package.json
Labels: enhancement

#1274 Create GH Action to Publish Project Automatically
  .github/workflows/NPM-Publish.yml
Labels: enhancement, good first issue

#1273 Refactor #1272: just a little bit refactoring.
  src/executable/TypiaSetupWizard.ts
  src/executable/setup/PackageManager.ts
Labels: enhancement

#1276 Optimize `typia.llm.application<App>()` function for bundling.
  benchmark/package.json
  errors/package.json
  package.json
  src/transformers/features/llm/LlmApplicationTransformer.ts
  test-esm/package.json
  test/package.json
Labels: enhancement

#1282 Add website dependabot
  .github/dependabot.yml
Labels: enhancement

#1290 Fix #1289: `typia.random<T>()` function for `uint` and `exlusiveMinimum`.
  .github/workflows/release.yml
  benchmark/package.json
  debug/package.json
  debug/src/llm.ts
  debug/src/random.ts
  deploy/internal/DeployRunner.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/helpers/RandomRanger.ts
  test-esm/package.json
  test/package.json
  test/src/features/issues/test_issue_1289_random_uint_exlcusiveMinimum.ts
  website/package.json
Labels: bug, enhancement

#1297 Add `tags.Example` type with `@samchon/openapi` upgrading.
  benchmark/package.json
  debug/package.json
  debug/src/llm.ts
  debug/src/random.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/llm/LlmApplicationProgrammer.ts
  src/tags/Example.ts
  src/tags/Examples.ts
  src/tags/index.ts
  test-esm/package.json
  test/package.json
  test/schemas/json/v3_0/UltimateUnion.json
  test/schemas/json/v3_1/UltimateUnion.json
  test/schemas/reflect/metadata/UltimateUnion.json
Labels: enhancement

#1298 Support `ILlmFunction.tags` by `@tag name` comment.
  benchmark/package.json
  debug/package.json
  debug/src/llm.ts
  errors/package.json
  package.json
  packages/typescript-json/package.json
  src/programmers/llm/LlmApplicationProgrammer.ts
  test-esm/package.json
  test/package.json
  test/src/features/llm.application/test_llm_application.ts
Labels: enhancement

#1304 Fix samchon/nestia#1043: object literal shorthand property problem.
  debug/package.json
  debug/src/shorthand.ts
  package.json
  src/factories/internal/metadata/emplace_metadata_object.ts
Labels: bug
