Repository samchon/typia, pull requests merged in 2025-03, with the labels that each got.

#1528 Re-wrote AI chatbot page
  website/pages/docs/llm/chat.mdx
Labels: documentation

#1537 Fix #1535: solve alias type case
  package.json
  src/programmers/json/JsonApplicationProgrammer.ts
  src/programmers/llm/LlmApplicationProgrammer.ts
  src/schemas/metadata/Metadata.ts
  test/src/debug/llm.ts
  test/src/features/issues/test_issue_1535_llm_application_pick.ts
Labels: bug

#1540 Fix typo of `@deprecated` tag.
  src/json.ts
Labels: bug, documentation

#1541 Detailed explanation of validation feedback strategy
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/chat.mdx
  website/pages/docs/llm/parameters.mdx
  website/pages/docs/llm/schema.mdx
  website/src/snippets/BbsArticleServiceSnippet.mdx
  website/src/snippets/IBbsArticleSnippet.mdx
  website/src/snippets/ILlmApplicationSnippet.mdx
  website/src/snippets/ILlmFunctionSnippet.mdx
  website/src/snippets/ILlmSchemaSnippet.mdx
  website/src/snippets/LlmApplicationExampleSnippet.mdx
  website/src/snippets/LlmApplicationJavaScriptSnippet.mdx
  website/src/snippets/LlmApplicationSeparateExampleSnippet.mdx
  website/src/snippets/LlmApplicationSeparateJsonSnippet.mdx
  website/src/snippets/LlmParametersExampleSnippet.mdx
  website/src/snippets/LlmParametersJavaScriptSnippet.mdx
  website/src/snippets/LlmSchemaExampleSnippet.mdx
  website/src/snippets/LlmSchemaJavaScriptSnippet.mdx
  website/src/snippets/ValidationFeedbackExampleSnippet.mdx
  website/src/snippets/ValidatorSupportMatrixSnippet.mdx
Labels: documentation

#1542 Fix `typia.llm.schema<T, Model>()` not to properly assign `$defs`.
  package.json
  src/transformers/features/llm/LlmSchemaTransformer.ts
  test/generate/input/generate_llm.ts
  test/generate/output/generate_llm.ts
  test/src/features/issues/test_issue_1390_llm_config_argument.ts
  test/src/features/issues/test_pr_1541_llm_schema_$defs.ts
Labels: bug, enhancement

#1543 Detailing of validation feedback strategy
  website/pages/docs/llm/application.mdx
  website/pages/docs/llm/chat.mdx
  website/pages/docs/llm/parameters.mdx
  website/src/snippets/ValidationFeedbackExampleSnippet.mdx
Labels: documentation, dependencies

#1554 chore: remove preinstall script (fixes: #1547)
  package.json
Labels: bug

#1556 Upgrade `@samchon/openapi`
  package.json
  pnpm-lock.yaml
Labels: dependencies
